/**
 * TileMap Resource Metadata Types
 *
 * Ambient type declarations for metadata parsed from tilemapresource.xml
 * files generated by gdal2tiles.
 *
 * CRITICAL NOTE ON RESOLUTION VALUES:
 * The `unitsPerPixel` values in `reportedTileSets` are the raster's native
 * resolution, NOT the actual tile grid resolution. Use the mission API's
 * `projResUnitsPerPixel` for TileGrid construction instead.
 * See AEGIS-MISSION-GIS.md Section 14 for full details.
 */

interface TilemapMetadata {
  /** Title from the XML (usually the source filename) */
  title: string;
  /** Spatial Reference System string */
  srs: string;
  /** Bounding box in projection units (meters for raster, degrees for mercator) */
  boundingBox: {
    minX: number;
    minY: number;
    maxX: number;
    maxY: number;
  };
  /** Tile grid origin (bottom-left for TMS) */
  origin: {
    x: number;
    y: number;
  };
  /** Tile format metadata */
  tileFormat: {
    width: number;
    height: number;
    mimeType: string;
    extension: string;
  };
  /** Tile profile: "mercator" or "raster" */
  profile: "mercator" | "raster";
  /**
   * Reported tile sets from the XML.
   *
   * WARNING: The `unitsPerPixel` values here are the raster's native resolution,
   * NOT the actual tile grid resolution used for tile coordinate calculation.
   * Do NOT use these for TileGrid construction. Use the mission API's
   * `projResUnitsPerPixel` instead.
   */
  reportedTileSets: Array<{
    zoom: number;
    unitsPerPixel: number;
  }>;
  /** Minimum zoom level available (from the first TileSet entry) */
  minZoom: number;
  /** Maximum zoom level available (from the last TileSet entry) */
  maxZoom: number;
}
