import { Seeder } from "@mikro-orm/seeder";
import { Dictionary, EntityManager } from "@mikro-orm/core";
import { Layer as Layer_db } from "../../models/layer.model";
import { v4 } from "uuid";

export class LayerSeeder extends Seeder {
  async run(em: EntityManager, context: Dictionary): Promise<void> {
    context.layer1 = em.create(Layer_db, {
      uuid: v4(),
      mission: context.mission1,
      layerConfig: {
        name: "Traverses",
        type: "header",
        demparser: "",
        controlled: false,
        tileformat: "tms",
        initialOpacity: 1,
        time: {
          enabled: false,
          type: "global",
          isRelative: true,
          current: new Date("2022-05-17T18:39:14Z"),
          start: "",
          end: "",
          format: "%Y-%m-%dT%H:%M:%SZ",
          refresh: "1 hours",
          increment: "5 minutes",
        },
        shape: "none",
        sublayers: [
          {
            //id: 1,
            name: "Apollo 14 Traverse",
            uuid: v4(),
            kind: "none",
            type: "vector",
            url: "Data/Apollo14Traverse.geojson",
            demparser: "",
            controlled: false,
            tileformat: "tms",
            visibility: false,
            initialOpacity: 1,
            togglesWithHeader: true,
            style: {
              className: "apollo14traverse",
              color: "#0075c0",
              fillColor: "#0075c0",
              weight: 1,
              fillOpacity: 1,
              opacity: 1,
            },
            variables: { useKeyAsName: "Shape_Leng" },
            radius: 1,
            time: {
              enabled: false,
              type: "global",
              isRelative: true,
              current: new Date("2022-05-17T18:39:14Z"),
              start: "",
              end: "",
              format: "%Y-%m-%dT%H:%M:%SZ",
              refresh: "1 hours",
              increment: "5 minutes",
            },
            shape: "none",
          },
        ],
      },
      createdAt: new Date(),
      updatedAt: new Date(),
    });
    context.layer2 = em.create(Layer_db, {
      uuid: v4(),
      mission: context.mission1,
      layerConfig: {
        name: "Sample Stations",
        type: "header",
        demparser: "",
        controlled: false,
        tileformat: "tms",
        initialOpacity: 1,
        time: {
          enabled: false,
          type: "global",
          isRelative: true,
          current: new Date("2022-05-17T18:39:14Z"),
          start: "",
          end: "",
          format: "%Y-%m-%dT%H:%M:%SZ",
          refresh: "1 hours",
          increment: "5 minutes",
        },
        shape: "none",
        sublayers: [
          {
            //id: 1,
            name: "Apollo 14 Sample Stations",
            uuid: v4(),
            kind: "none",
            type: "vector",
            url: "Data/Apollo14.geojson",
            demparser: "",
            controlled: false,
            tileformat: "tms",
            visibility: false,
            initialOpacity: 1,
            togglesWithHeader: true,
            style: {
              className: "apollo14samplestations",
              color: "#0075c0",
              fillColor: "#0075c0",
              weight: 1,
              fillOpacity: 1,
              opacity: 1,
            },
            variables: { useKeyAsName: "Name" },
            radius: 4,
            time: {
              enabled: false,
              type: "global",
              isRelative: true,
              current: new Date("2022-05-17T18:39:14Z"),
              start: "",
              end: "",
              format: "%Y-%m-%dT%H:%M:%SZ",
              refresh: "1 hours",
              increment: "5 minutes",
            },
            shape: "none",
          },
        ],
      },
      createdAt: new Date(),
      updatedAt: new Date(),
    });
    context.layer3 = em.create(Layer_db, {
      uuid: v4(),
      mission: context.mission1,
      layerConfig: {
        name: "Detrended Roughness",
        type: "header",
        demparser: "",
        controlled: false,
        tileformat: "tms",
        initialOpacity: 1,
        time: {
          enabled: false,
          type: "global",
          isRelative: true,
          current: new Date("2022-05-17T18:39:14Z"),
          start: "",
          end: "",
          format: "%Y-%m-%dT%H:%M:%SZ",
          refresh: "1 hours",
          increment: "5 minutes",
        },
        shape: "none",
        sublayers: [
          {
            //id: 1,
            name: "NAC DTM DTR 2m ",
            uuid: v4(),
            type: "tile",
            url: "Layers/NAC_DTM_DTR_2m/{z}/{x}/{y}.png",
            demtileurl: "Layers/NAC_DTM_2m_v2/{z}/{x}/{y}.png",
            demparser: "",
            controlled: false,
            tileformat: "tms",
            visibility: false,
            initialOpacity: 1,
            togglesWithHeader: true,
            minZoom: 8,
            maxNativeZoom: 14,
            maxZoom: 23,
            boundingBox: [
              -17.52243003485202, -3.90650040991372, -17.39118264564012, -2.96897224131543,
            ],
            time: {
              enabled: false,
              type: "global",
              isRelative: true,
              current: new Date("2022-05-17T18:39:14Z"),
              start: "",
              end: "",
              format: "%Y-%m-%dT%H:%M:%SZ",
              refresh: "1 hours",
              increment: "5 minutes",
            },
            shape: "none",
          },
        ],
      },
      createdAt: new Date(),
      updatedAt: new Date(),
    });
    context.layer4 = em.create(Layer_db, {
      uuid: v4(),
      mission: context.mission1,
      layerConfig: {
        name: "Confidence Map",
        type: "header",
        demparser: "",
        controlled: false,
        tileformat: "tms",
        initialOpacity: 1,
        time: {
          enabled: false,
          type: "global",
          isRelative: true,
          current: new Date("2022-05-17T18:39:14Z"),
          start: "",
          end: "",
          format: "%Y-%m-%dT%H:%M:%SZ",
          refresh: "1 hours",
          increment: "5 minutes",
        },
        shape: "none",
        sublayers: [
          {
            //id: 1,
            name: "NAC DTM 2m Confidence Map",
            uuid: v4(),
            type: "tile",
            url: "Layers/NAC_DTM_2m_confidence_map/{z}/{x}/{y}.png",
            demparser: "",
            controlled: false,
            tileformat: "tms",
            visibility: false,
            initialOpacity: 1,
            togglesWithHeader: true,
            minZoom: 8,
            maxNativeZoom: 14,
            maxZoom: 23,
            boundingBox: [
              -17.52838060176, -3.91301487948368, -17.38598936240026, -2.96326094389799,
            ],
            time: {
              enabled: false,
              type: "global",
              isRelative: true,
              current: new Date("2022-05-17T18:39:14Z"),
              start: "",
              end: "",
              format: "%Y-%m-%dT%H:%M:%SZ",
              refresh: "1 hours",
              increment: "5 minutes",
            },
            shape: "none",
          },
        ],
      },
      createdAt: new Date(),
      updatedAt: new Date(),
    });
    context.layer5 = em.create(Layer_db, {
      uuid: v4(),
      mission: context.mission1,
      layerConfig: {
        name: "Hillshade",
        type: "header",
        demparser: "",
        controlled: false,
        tileformat: "tms",
        initialOpacity: 1,
        time: {
          enabled: false,
          type: "global",
          isRelative: true,
          current: new Date("2022-05-17T18:39:14Z"),
          start: "",
          end: "",
          format: "%Y-%m-%dT%H:%M:%SZ",
          refresh: "1 hours",
          increment: "5 minutes",
        },
        shape: "none",
        sublayers: [
          {
            //id: 1,
            name: "NAC DTM 2m Hillshade",
            uuid: v4(),
            type: "tile",
            url: "Layers/NAC_DTM_hillshade/{z}/{x}/{y}.png",
            demparser: "",
            controlled: false,
            tileformat: "tms",
            visibility: false,
            initialOpacity: 1,
            togglesWithHeader: true,
            minZoom: 8,
            maxNativeZoom: 14,
            maxZoom: 23,
            boundingBox: [
              -17.52838060176, -3.91301487948368, -17.38598936240026, -2.96326094389799,
            ],
            time: {
              enabled: false,
              type: "global",
              isRelative: true,
              current: new Date("2022-05-17T18:39:14Z"),
              start: "",
              end: "",
              format: "%Y-%m-%dT%H:%M:%SZ",
              refresh: "1 hours",
              increment: "5 minutes",
            },
            shape: "none",
          },
        ],
      },
      createdAt: new Date(),
      updatedAt: new Date(),
    });
    context.layer6 = em.create(Layer_db, {
      uuid: v4(),
      mission: context.mission1,
      layerConfig: {
        name: "Basemaps",
        type: "header",
        demparser: "",
        controlled: false,
        tileformat: "tms",
        initialOpacity: 1,
        time: {
          enabled: false,
          type: "global",
          isRelative: true,
          current: new Date("2022-05-17T18:39:14Z"),
          start: "",
          end: "",
          format: "%Y-%m-%dT%H:%M:%SZ",
          refresh: "1 hours",
          increment: "5 minutes",
        },
        shape: "none",
        sublayers: [
          {
            //id: 1,
            name: "NAC Ortho 50cm M150639913",
            uuid: v4(),
            type: "tile",
            url: "Layers/NAC_ortho_50cm_2/{z}/{x}/{y}.png",
            aegisURL: "NAC_ortho_50cm_2/{z}/{x}/{y}.png",
            demparser: "",
            controlled: false,
            tileformat: "tms",
            visibility: false,
            initialOpacity: 1,
            togglesWithHeader: true,
            minZoom: 8,
            maxNativeZoom: 16,
            maxZoom: 23,
            boundingBox: [-17.5283310671, -3.91299838779177, -17.38598938443003, -2.963277432841],
            time: {
              enabled: false,
              type: "global",
              isRelative: true,
              current: new Date("2022-05-17T18:39:14Z"),
              start: "",
              end: "",
              format: "%Y-%m-%dT%H:%M:%SZ",
              refresh: "1 hours",
              increment: "5 minutes",
            },
            shape: "none",
          },
          {
            //id: 2,
            name: "NAC Ortho 50cm M150633128",
            uuid: v4(),
            type: "tile",
            url: "Layers/NAC_ortho_50cm_1_v4/{z}/{x}/{y}.png",
            aegisURL: "NAC_ortho_50cm_1_v4/{z}/{x}/{y}.png",
            demtileurl: "Layers/NAC_DTM_2m_v2/{z}/{x}/{y}.png",
            demparser: "",
            controlled: false,
            tileformat: "tms",
            visibility: true,
            initialOpacity: 1,
            togglesWithHeader: true,
            minZoom: 8,
            maxNativeZoom: 16,
            maxZoom: 23,
            boundingBox: [
              -17.52243003485202, -3.90647227279352, -17.39118427681328, -2.96897224131543,
            ],
            time: {
              enabled: false,
              type: "global",
              isRelative: true,
              current: new Date("2022-05-17T18:39:14Z"),
              start: "",
              end: "",
              format: "%Y-%m-%dT%H:%M:%SZ",
              refresh: "1 hours",
              increment: "5 minutes",
            },
            shape: "none",
          },
        ],
      },
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  }
}
