import { Seeder } from "@mikro-orm/seeder";
import { Dictionary, EntityManager } from "@mikro-orm/core";
import { Mission } from "../../models/mission.model";

export class MissionSeeder extends Seeder {
  async run(em: EntityManager, context: Dictionary): Promise<void> {
    context.mission = em.create(Mission, {
      name: "Apollo_14",
      config: {
        msv: {
          mission: "Apollo_14",
          site: "",
          masterdb: false,
          view: ["-3.64602", "-17.47204", "14"],
          radius: { major: "1737400", minor: "1737400" },
          mapscale: "",
        },
        projection: {
          custom: false,
          epsg: "EPSG:3857",
          proj: "+proj=merc +a=1737400 +b=1737400 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs",
          xmlpath: "",
          bounds: [
            "-17.52833106710000",
            "-3.91299838779177",
            "-17.38598938443003",
            "-2.96327743284100",
          ],
          origin: ["-17.52833106710000", "-3.91299838779177"],
          reszoomlevel: 8,
          resunitsperpixel: 611.49622617187504,
        },
        look: {
          pagename: "postgres",
          minimalist: false,
          zoomcontrol: true,
          graticule: false,
          coordll: true,
          coorden: true,
          coordrxy: true,
          coordsite: false,
          coordelev: false,
          coordelevurl: "",
          coordlngoffset: "",
          coordlatoffset: "",
          coordeastoffset: "",
          coordnorthoffset: "",
          coordeastmult: "",
          coordnorthmult: "",
          primarycolor: "",
          secondarycolor: "",
          tertiarycolor: "",
          accentcolor: "",
          bodycolor: "",
          topbarcolor: "",
          toolbarcolor: "",
          mapcolor: "",
          highlightcolor: "",
          copylink: true,
          screenshot: true,
          fullscreen: true,
          help: true,
          logourl: "",
          helpurl: "",
        },
        panels: ["viewer", "map", "globe"],
        panelSettings: { demFallbackPath: "", demFallbackFormat: null, demFallbackType: null },
        tools: [
          { name: "Layers", icon: "buffer", js: "LayersTool" },
          { name: "Legend", icon: "format-list-bulleted-type", js: "LegendTool" },
          { name: "Info", icon: "information-variant", js: "InfoTool" },
          {
            name: "Sites",
            icon: "pin",
            js: "SitesTool",
            variables: {
              sites: [{ name: "Landing Site", code: "LS", view: [-3.64602, -17.47204, 14] }],
            },
          },
          {
            name: "Isochrone",
            icon: "circle-double",
            js: "IsochroneTool",
            variables: {
              data: {
                DEM: [
                  {
                    name: "NAC Ortho 50cm M150633128",
                    tileurl: "Layers/NAC_ortho_50cm_1_v4/{z}/{x}/{y}.png",
                    minZoom: 8,
                    maxNativeZoom: 18,
                    resolution: 256,
                    interpolateSeams: true,
                  },
                ],
                slope: [{ "...": "..." }],
                cost: [{ "...": "..." }],
              },
              interpolateSeams: false,
              models: ["Traverse Time", "Isodistance", "..."],
            },
          },
          { name: "Chemistry", icon: "flask", js: "ChemistryTool" },
          { name: "Draw", icon: "lead-pencil", js: "DrawTool" },
          {
            name: "Identifier",
            icon: "map-marker",
            js: "IdentifierTool",
            variables: { tile_with_DEM: { url: "Data/missionDEM.tif", unit: "m" } },
          },
          {
            name: "Measure",
            icon: "chart-areaspline",
            js: "MeasureTool",
            variables: { dem: "Data/missionDEM.tif" },
          },
        ],
        time: { enabled: false, visible: false, format: "" },
      },
      version: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
    em.create(Mission, {
      name: "Potrillo_VF_v001",
      config: {
        msv: {
          mission: "Potrillo_VF_v001",
          site: "",
          masterdb: false,
          view: ["31.970525", "-106.963026", "11"],
          radius: { major: "6378137", minor: "6378137" },
          mapscale: "",
        },
        projection: {
          custom: false,
          epsg: "",
          proj: "",
          xmlpath: "",
          bounds: [
            "-107.47297700557911",
            "31.65986801717055",
            "-106.55954285121517",
            "32.28391307648736",
          ],
          origin: ["-107.47297700557911", "31.65986801717055"],
          reszoomlevel: 8,
          resunitsperpixel: 611.49622617187504,
        },
        look: {
          pagename: "postgres",
          minimalist: false,
          zoomcontrol: true,
          graticule: false,
          coordll: true,
          coorden: true,
          coordrxy: true,
          coordsite: false,
          coordelev: false,
          coordelevurl: "",
          coordlngoffset: "",
          coordlatoffset: "",
          coordeastoffset: "",
          coordnorthoffset: "",
          coordeastmult: "",
          coordnorthmult: "",
          primarycolor: "",
          secondarycolor: "",
          tertiarycolor: "#ffffff",
          accentcolor: "#B2DFDB",
          bodycolor: "",
          topbarcolor: "#00796B",
          toolbarcolor: "#009688",
          mapcolor: "",
          highlightcolor: "",
          copylink: true,
          screenshot: true,
          fullscreen: true,
          help: true,
          logourl: "",
          helpurl: "",
        },
        panels: ["viewer", "map", "globe"],
        panelSettings: { demFallbackPath: "", demFallbackFormat: null, demFallbackType: null },
        tools: [
          { name: "Layers", icon: "buffer", js: "LayersTool" },
          { name: "Legend", icon: "format-list-bulleted-type", js: "LegendTool" },
          { name: "Info", icon: "information-variant", js: "InfoTool" },
          {
            name: "Sites",
            icon: "pin",
            js: "SitesTool",
            variables: {
              sites: [{ name: "Site1", code: "S1", view: [31.970525, -106.963026, 14] }],
            },
          },
          {
            name: "Isochrone",
            icon: "circle-double",
            js: "IsochroneTool",
            variables: {
              data: {
                DEM: [
                  {
                    name: "DEM",
                    tileurl: "Layers/portrillo_DEM/{z}/{x}/{y}.png",
                    minZoom: 0,
                    maxNativeZoom: 17,
                    resolution: 32,
                    interpolateSeams: true,
                  },
                ],
              },
              models: ["Traverse Time", "Isodistance"],
            },
          },
          {
            name: "Viewshed",
            icon: "wifi-strength-2",
            js: "ViewshedTool",
            variables: {
              data: [
                {
                  name: "DEM",
                  demtileurl: "Layers/portrillo_DEM/{z}/{x}/{y}.png",
                  minZoom: 0,
                  maxNativeZoom: 17,
                },
              ],
            },
          },
          { name: "Draw", icon: "lead-pencil", js: "DrawTool" },
          {
            name: "Identifier",
            icon: "map-marker",
            js: "IdentifierTool",
            variables: { tile_with_DEM: { url: "Data/missionDEM.tif", unit: "m" } },
          },
          {
            name: "Measure",
            icon: "chart-areaspline",
            js: "MeasureTool",
            variables: { dem: "Data/3DEP_DEM_10M/kilbournehole_10m_dem_3857.tif" },
          },
        ],
        time: { enabled: false, visible: false, format: "" },
      },
      version: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
    em.create(Mission, {
      name: "Test",
      config: {
        msv: {
          mission: "Test",
          site: "",
          masterdb: false,
          view: ["0", "0", "0"],
          radius: { major: "3396190", minor: "3396190" },
          mapscale: "",
        },
        projection: {
          custom: false,
          epsg: "",
          proj: "",
          globeproj: "webmercator",
          xmlpath: "",
          bounds: ["", "", "", ""],
          origin: ["", ""],
          reszoomlevel: 0,
          resunitsperpixel: 0,
        },
        look: {
          pagename: "postgres",
          minimalist: false,
          zoomcontrol: false,
          graticule: false,
          bodycolor: "",
          topbarcolor: "",
          toolbarcolor: "",
          mapcolor: "",
          swap: true,
          copylink: true,
          screenshot: true,
          fullscreen: true,
          help: true,
          logourl: "",
          helpurl: "",
        },
        panels: ["viewer", "map", "globe"],
        time: {
          enabled: false,
          visible: false,
          format: "%Y-%m-%dT%H:%M:%SZ",
        },
        tools: [
          { name: "Layers", icon: "buffer", js: "LayersTool" },
          { name: "Legend", icon: "format-list-bulleted-type", js: "LegendTool" },
          { name: "Info", icon: "information-variant", js: "InfoTool" },
          {
            name: "Sites",
            icon: "pin",
            js: "SitesTool",
            variables: {
              sites: [
                { name: "Site1", code: "S1", view: [-4.667975771815966, 137.370253354311, 16] },
                { name: "Site2", code: "S2", view: [-4.667985128408622, 137.3702734708786, 20] },
              ],
            },
          },
          { name: "Chemistry", icon: "flask", js: "ChemistryTool" },
          { name: "Draw", icon: "lead-pencil", js: "DrawTool" },
          { name: "FileManager", icon: "folder-multiple", js: "FileManagerTool" },
          {
            name: "Identifier",
            icon: "map-marker",
            js: "IdentifierTool",
            variables: { tile_with_DEM: { url: "Data/missionDEM.tif", unit: "m" } },
          },
          {
            name: "Measure",
            icon: "chart-areaspline",
            js: "MeasureTool",
            variables: { dem: "Data/missionDEM.tif" },
          },
        ],
      },
      version: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  }
}
