import { MikroORM } from "@mikro-orm/postgresql";
import config from "server/database/mikro-orm.config";
import { globalValues } from "server/express/global";
import { Eva_db, Rex_db, Doc_Listing_db } from "server/database/models/_allModels";
import EvaFactory from "../../fixtures/entityFactories/EVAFactory";
import RexFactory from "tests/vitest/fixtures/entityFactories/RexFactory";
import DocListingFactory from "../../fixtures/entityFactories/DocListingFactory";
import supertest from "supertest";
import app from "server/express/restApi";
import { createMockAutomergeRepo } from "../../helpers/mockAutomergeRepo";

let testEvas: Eva_db[];
let testRexes: Rex_db[];
let testAutomergeDocListings: Doc_Listing_db[];
let testMissionsPartial: Partial<Mission>[];
const emssToken = process.env.EMSS_TOKEN;

beforeAll(async () => {
  // Initialize MikroORM and set it in globalValues
  globalValues.orm = await MikroORM.init(config);
  const em = globalValues.orm.em.fork();

  // Create test missions
  // First create Doc_Listing_db records to get autogenerated IDs
  testAutomergeDocListings = await new DocListingFactory(em)
    .each((record, index) => {
      record.automergeUrl = `automerge:VitestTestMission${index + 1}`;
    })
    .create(3);
  // Then create testMissionsPartial using the autogenerated IDs from the automerge records
  testMissionsPartial = [
    {
      id: testAutomergeDocListings[0].missionId,
      name: "Vitest Test Mission 1",
      isArchived: false,
      actionSystemVersion: 2,
    },
    {
      id: testAutomergeDocListings[1].missionId,
      name: "Vitest Test Mission 2",
      isArchived: false,
      actionSystemVersion: 2,
    },
    {
      id: testAutomergeDocListings[2].missionId,
      name: "Vitest Test Mission 3", // this mission is a v1 mission
      isArchived: false,
      actionSystemVersion: 1,
    },
  ];
  // Last, create mock automerge repo with test missions partials from above
  globalValues.automergeRepo = createMockAutomergeRepo(testMissionsPartial);

  // EVAs for testMissionsPartial[0]
  const testEvasWithRexes = await new EvaFactory(em)
    .each((eva, idx) => {
      eva.missionId = testMissionsPartial[0].id;
      eva.name = `Vitest EVA With Rexes ${idx}`;
    })
    .create(2);
  const testEvasWithoutRexes = await new EvaFactory(em)
    .each((eva, idx) => {
      eva.missionId = testMissionsPartial[0].id;
      eva.name = `Vitest EVA Without Rexes ${idx}`;
    })
    .create(2);
  // EVA for testMissionPartial[2] (V1 mission)
  const testEvaOnV1Missions = await new EvaFactory(em)
    .each((eva) => {
      eva.missionId = testMissionsPartial[2].id;
      eva.name = `Vitest EVA on V1 Mission`;
    })
    .create(1);

  testEvas = [...testEvasWithRexes, ...testEvasWithoutRexes, ...testEvaOnV1Missions];

  // Create REXes for two of the EVAs
  testRexes = await new RexFactory(em)
    .each((rex, idx) => {
      rex.missionId = testMissionsPartial[0].id;
      rex.evaUuid = testEvasWithRexes[idx].uuid;
      rex.name = `Vitest REX-${idx}`;
    })
    .create(2);
});

describe("GET MISSIONS Endpoint", () => {
  describe("Authentication", () => {
    test("Fails without emss-token", async () => {
      const res = await supertest(app).get("/api/v1/emss/getMissions");
      expect(res.statusCode).toBe(401);
      expect(res.body.status).toBe("failure");
      expect(res.body.message).toBe("Unauthorized");
    });

    test("Fails with invalid emss-token", async () => {
      const res = await supertest(app)
        .get("/api/v1/emss/getMissions")
        .set("emss-token", "invalid-token");
      expect(res.statusCode).toBe(401);
      expect(res.body.status).toBe("failure");
      expect(res.body.message).toBe("Unauthorized");
    });
  });

  describe("Missions functionality", () => {
    test("Retrieves all missions", async () => {
      const res = await supertest(app).get("/api/v1/emss/getMissions").set("emss-token", emssToken);

      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");

      const missions = res.body.data;
      // v2 missions are included, v1 mission is not
      expect(missions[testMissionsPartial[0].id]).toBeDefined();
      expect(missions[testMissionsPartial[1].id]).toBeDefined();
      expect(missions[testMissionsPartial[2].id]).toBeDefined();
    });

    test("Retrieves only as-planned EVAs", async () => {
      const res = await supertest(app).get("/api/v1/emss/getMissions").set("emss-token", emssToken);

      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");

      const missions: MissionsWithEvas = res.body.data;
      expect(missions[testMissionsPartial[0].id]).toBeDefined();
      expect(missions[testMissionsPartial[0].id].evas).toHaveLength(2);
      const rexEvaUuids = testRexes.map((rex) => rex.evaUuid);
      expect(
        missions[testMissionsPartial[0].id].evas.some((eva) => rexEvaUuids.includes(eva.refUuid))
      ).toBe(false); // no rex eva uuids should be included in the results
    });

    test("Returns empty data for mission with no EVAs", async () => {
      const res = await supertest(app).get("/api/v1/emss/getMissions").set("emss-token", emssToken);
      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      const missions: MissionsWithEvas = res.body.data;
      expect(missions[testMissionsPartial[1].id]).toBeDefined();
      expect(missions[testMissionsPartial[1].id].evas).toHaveLength(0); // No evas on this mission
    });

    test("EVAs contains correct structure", async () => {
      const res = await supertest(app).get("/api/v1/emss/getMissions").set("emss-token", emssToken);

      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      expect(res.body.message).toBe("Missions and their EVAs retrieved");

      const mission1Data = res.body.data[testMissionsPartial[0].id];
      const eva = mission1Data.evas[0];

      expect(eva).toHaveProperty("refUuid");
      expect(eva).toHaveProperty("evaName");
    });
  });
});

afterAll(async () => {
  const em = globalValues.orm.em.fork();
  for (const rex of testRexes) {
    await em.nativeDelete(Rex_db, { uuid: rex.uuid });
  }
  for (const eva of testEvas) {
    await em.nativeDelete(Eva_db, { uuid: eva.uuid });
  }
  for (let i = 0; i < testAutomergeDocListings.length; i++) {
    await em.nativeDelete(Doc_Listing_db, { missionId: testAutomergeDocListings[i].missionId });
  }
  await globalValues.orm.close();
  globalValues.orm = null;
  vi.restoreAllMocks();
});
