import { MikroORM } from "@mikro-orm/postgresql";
import config from "server/database/mikro-orm.config";
import { globalValues } from "server/express/global";
import { Eva_db, Rex_db, Doc_Listing_db } from "server/database/models/_allModels";
import EvaFactory from "../../fixtures/entityFactories/EVAFactory";
import RexFactory from "../../fixtures/entityFactories/RexFactory";
import DocListingFactory from "../../fixtures/entityFactories/DocListingFactory";
import supertest from "supertest";
import app from "server/express/restApi";
import { createMockAutomergeRepo } from "../../helpers/mockAutomergeRepo";

let testEvas: Eva_db[];
let testRexes: Rex_db[];
let testAutomergeDocListings: Doc_Listing_db[];
let testMissionsPartial: Partial<Mission>[];
const emssToken = process.env.EMSS_TOKEN;

beforeAll(async () => {
  // Initialize MikroORM and set it in globalValues
  globalValues.orm = await MikroORM.init(config);
  const em = globalValues.orm.em.fork();

  // Create a test mission
  // First create Doc_Listing_db records to get autogenerated IDs
  testAutomergeDocListings = await new DocListingFactory(em)
    .each((record) => {
      record.automergeUrl = `automerge:VitestTestMissionGetRexesByEvaRef`;
    })
    .create(1);
  // Then create testMissionsPartial using the autogenerated IDs from the automerge records
  testMissionsPartial = [
    {
      id: testAutomergeDocListings[0].missionId,
      name: "Vitest Test Mission GetRexesByEvaRef",
      isArchived: false,
    },
  ];
  // Last, create mock automerge repo with test missions partials from above
  globalValues.automergeRepo = createMockAutomergeRepo(testMissionsPartial);

  // create 3 EVAs with the same refUuid, (1 as-planned, 2 executed)
  // create 2 REXes linked to the first 2 EVAs
  testEvas = await new EvaFactory(em)
    .each((eva) => {
      eva.missionId = testMissionsPartial[0].id;
      eva.refUuid = `some-ref-uuid`;
    })
    .create(3);

  testRexes = await new RexFactory(em)
    .each((rex, idx) => {
      rex.missionId = testMissionsPartial[0].id;
      rex.evaUuid = testEvas[idx].uuid;
    })
    .create(2);
});

describe("GET REX BY EVA REF Endpoint", () => {
  describe("Authentication", () => {
    test("Fails without emss-token", async () => {
      const res = await supertest(app)
        .get("/api/v1/emss/getRexesByEvaRef")
        .query({ evaRefUuid: testEvas[0].refUuid });
      expect(res.statusCode).toBe(401);
      expect(res.body.status).toBe("failure");
      expect(res.body.message).toBe("Unauthorized");
    });

    test("Fails with invalid emss-token", async () => {
      const res = await supertest(app)
        .get("/api/v1/emss/getRexesByEvaRef")
        .set("emss-token", "invalid-token")
        .query({ evaRefUuid: testEvas[0].refUuid });
      expect(res.statusCode).toBe(401);
      expect(res.body.status).toBe("failure");
      expect(res.body.message).toBe("Unauthorized");
    });
  });

  describe("Eva Ref validation", () => {
    test("Errors for missing evaRefUuid", async () => {
      const res = await supertest(app)
        .get("/api/v1/emss/getRexesByEvaRef")
        .set("emss-token", emssToken);
      expect(res.statusCode).toBe(400);
      expect(res.body.status).toBe("failure");
      expect(res.body.message).toContain("No EVA Ref given");
    });
  });

  describe("Eva Ref functionality", () => {
    test("Returns empty array for non-existent ref", async () => {
      const res = await supertest(app)
        .get("/api/v1/emss/getRexesByEvaRef")
        .set("emss-token", emssToken)
        .query({ evaRefUuid: "non-existent-ref" });
      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      expect(res.body.data).toEqual([]);
    });

    test("Retrieves rexes for existing ref", async () => {
      const res = await supertest(app)
        .get("/api/v1/emss/getRexesByEvaRef")
        .set("emss-token", emssToken)
        .query({ evaRefUuid: testEvas[0].refUuid });
      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      expect(res.body.message).toContain("Rexes retrieved");
      expect(res.body.data.length).toBe(2);
      const uuids = res.body.data.map((r: { uuid: string }) => r.uuid);
      expect(uuids).toEqual(expect.arrayContaining([testRexes[0].uuid, testRexes[1].uuid]));
    });

    test("Does not retrieve rex if it has a maestroEventId", async () => {
      // First, update one rex to have a maestroEventId
      const em = globalValues.orm.em.fork();
      const rexToUpdate = await em.findOne(Rex_db, { uuid: testRexes[0].uuid });
      rexToUpdate.maestroEventId = "some-event-uuid";
      await em.flush();

      const res = await supertest(app)
        .get("/api/v1/emss/getRexesByEvaRef")
        .set("emss-token", emssToken)
        .query({ evaRefUuid: testEvas[0].refUuid });
      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      expect(res.body.message).toContain("Rexes retrieved");
      expect(res.body.data.length).toBe(1);
      expect(res.body.data[0].uuid).toBe(testRexes[1].uuid);
    });
  });
});

afterAll(async () => {
  const em = globalValues.orm.em.fork();
  for (const rex of testRexes) {
    await em.nativeDelete(Rex_db, { uuid: rex.uuid });
  }
  for (const eva of testEvas) {
    await em.nativeDelete(Eva_db, { uuid: eva.uuid });
  }
  for (let i = 0; i < testAutomergeDocListings.length; i++) {
    await em.nativeDelete(Doc_Listing_db, { missionId: testAutomergeDocListings[i].missionId });
  }
  await globalValues.orm.close();
  globalValues.orm = null;
  vi.restoreAllMocks();
});
