import { MikroORM } from "@mikro-orm/postgresql";
import config from "server/database/mikro-orm.config";
import { globalValues } from "server/express/global";
import {
  Rex_db,
  Eva_db,
  Station_db,
  Traverse_db,
  Action_db,
  Doc_Listing_db,
} from "server/database/models/_allModels";
import RexFactory from "../../fixtures/entityFactories/RexFactory";
import DocListingFactory from "../../fixtures/entityFactories/DocListingFactory";
import EvaFactory from "tests/vitest/fixtures/entityFactories/EVAFactory";
import StationFactory from "tests/vitest/fixtures/entityFactories/StationFactory";
import TraverseFactory from "tests/vitest/fixtures/entityFactories/TraverseFactory";
import ActionFactory from "tests/vitest/fixtures/entityFactories/ActionFactory";
import * as SocketIo from "server/express/sockets";
import supertest from "supertest";
import app from "server/express/restApi";
import { createMockAutomergeRepo } from "../../helpers/mockAutomergeRepo";

// suppress socketio calls because they won't work during vitest testing
vi.mock("server/express/sockets", async () => {
  const actual = await vi.importActual("server/express/sockets");
  return {
    ...actual,
    emitStoreUpsert: vi.fn(),
    emitStoreDelete: vi.fn(),
  };
});

let testRexes: Rex_db[];
let testEva: Eva_db;
let testStation: Station_db;
let testTraverse: Traverse_db;
let testStationAction: Action_db;
let testAutomergeDocListings: Doc_Listing_db[];
let testMissionsPartial: Partial<Mission>[];
const emssToken = process.env.EMSS_TOKEN;
let validRexOverwrite: RexOverwrite;

beforeAll(async () => {
  // Initialize MikroORM and set it in globalValues
  globalValues.orm = await MikroORM.init(config);
  const em = globalValues.orm.em.fork();

  // Create a test mission
  // First create Doc_Listing_db records to get autogenerated IDs
  testAutomergeDocListings = await new DocListingFactory(em)
    .each((record) => {
      record.automergeUrl = `automerge:VitestTestMissionRexOverwrite`;
    })
    .create(1);
  // Then create testMissionsPartial using the autogenerated IDs from the automerge records
  testMissionsPartial = [
    {
      id: testAutomergeDocListings[0].missionId,
      name: "Vitest Test Mission RexOverwrite",
      isArchived: false,
    },
  ];
  // Last, create mock automerge repo with test missions partials from above
  globalValues.automergeRepo = createMockAutomergeRepo(testMissionsPartial);
  testStation = await new StationFactory(em)
    .each((station) => {
      station.missionId = testMissionsPartial[0].id;
    })
    .createOne();
  testTraverse = await new TraverseFactory(em)
    .each((traverse) => {
      traverse.missionId = testMissionsPartial[0].id;
    })
    .createOne();
  testStationAction = await new ActionFactory(em)
    .each((action) => {
      action.missionId = testMissionsPartial[0].id;
      action.station = testStation;
    })
    .createOne();
  testEva = await new EvaFactory(em)
    .each((eva) => {
      eva.missionId = testMissionsPartial[0].id;
      eva.sequence = [
        { type: "traverse", uuid: testTraverse.uuid },
        { type: "station", uuid: testStation.uuid },
      ];
    })
    .createOne();
  testRexes = await new RexFactory(em)
    .each((rex, idx) => {
      rex.name = `Vitest Rex rexOverwrite ${idx + 1}`;
      rex.missionId = testMissionsPartial[0].id;
      rex.evaUuid = testEva.uuid;
      rex.isRunning = idx === 1; // create one rex that is running, one that is not
    })
    .create(2);

  // populate a valid rexOverwrite object for use in tests
  validRexOverwrite = {
    uuid: testRexes[0].uuid,
    petStartStopTimestamp: "2025-09-04T01:00:00Z",
    petValueAtStartStop: "00:05:30",
    petRunning: true,
    maestroControlled: true,
    isRunning: true,
    maestroEventId: "111-222-333-444-555-666",
    maestroEventUrl: "https://maestro-server.example.com/events/111-222-333-444-555-666",
    maestroActivityPropertiesByRefUuid: {
      egress: {
        color: "#ff0000",
        number: "1",
      },
      [testStation.refUuid]: {
        color: "#00ffff",
        number: "2A",
      },
      [testTraverse.refUuid]: {
        color: "#0000ff",
        number: "3",
      },
    },
    stationEntriesByRefUuid: {
      [testStation.refUuid]: {
        rexStatus: "complete",
        maestroPercentCompleteEv1: 0,
        maestroPercentCompleteEv2: 100,
      },
    },
    traverseEntriesByRefUuid: {
      [testTraverse.refUuid]: {
        rexStatus: "in-progress",
        maestroPercentCompleteEv1: 20,
        maestroPercentCompleteEv2: 80,
      },
    },
    actionEntriesByRefUuid: {
      [testStationAction.refUuid]: {
        rexStatus: "complete",
        markerId: "marker-123",
      },
    },
    xgressEntries: {
      egress: {
        rexStatus: "complete",
      },
      ingress: {
        rexStatus: "in-progress",
      },
    },
  };
});

beforeEach(async () => {
  vi.clearAllMocks(); // clear call count
});

describe("REX Status API Endpoint", () => {
  describe("POST request - Authentication", () => {
    test("Returns auth failure without emss-token", async () => {
      const response = await supertest(app).post("/api/v1/emss/rexOverwrite").send({});
      expect(response.status).toBe(401);
      expect(response.body).toEqual({
        status: "failure",
        message: "Unauthorized",
      });
    });

    test("Returns auth failure with invalid emss-token", async () => {
      const response = await supertest(app)
        .post("/api/v1/emss/rexOverwrite")
        .set("emss-token", "invalid_token")
        .send({});
      expect(response.status).toBe(401);
      expect(response.body).toEqual({
        status: "failure",
        message: "Unauthorized",
      });
    });
  });

  describe("POST request - Validation", () => {
    test("Fails schema validation with invalid payload", async () => {
      const response = await supertest(app)
        .post("/api/v1/emss/rexOverwrite")
        .set("emss-token", emssToken)
        .send({ invalidField: "value" });
      expect(response.status).toBe(400);
      expect(response.body.status).toBe("failure");
    });

    test("Fails if rexUuid is not a valid UUID", async () => {
      const response = await supertest(app)
        .post("/api/v1/emss/rexOverwrite")
        .set("emss-token", emssToken)
        .send({ ...validRexOverwrite, uuid: "invalid-uuid" });
      expect(response.status).toBe(400);
      expect(response.body.message).toBe("rexUuid must be a valid UUID.");
    });

    test("Fails if petRunning is true but isRunning is false", async () => {
      const response = await supertest(app)
        .post("/api/v1/emss/rexOverwrite")
        .set("emss-token", emssToken)
        .send({ ...validRexOverwrite, petRunning: true, isRunning: false });
      expect(response.status).toBe(400);
      expect(response.body.message).toBe(
        "Rex must be running (isRunning=true) in order to set petRunning=true."
      );
    });

    test("Fails if petValueAtStartStop is not in HHMMSS format", async () => {
      const response = await supertest(app)
        .post("/api/v1/emss/rexOverwrite")
        .set("emss-token", emssToken)
        .send({ ...validRexOverwrite, petValueAtStartStop: "invalid" });
      expect(response.status).toBe(400);
      expect(response.body.message).toBe("PetValueAtStartStop must be HHMMSS format.");
    });

    test("Fails if petStartStopTimestamp is not an ISO string", async () => {
      const response = await supertest(app)
        .post("/api/v1/emss/rexOverwrite")
        .set("emss-token", emssToken)
        .send({ ...validRexOverwrite, petStartStopTimestamp: "invalid" });
      expect(response.status).toBe(400);
      expect(response.body.message).toBe("petStartStopTimestamp must be an ISO String format.");
    });

    test("Fails if maestroEventUrl is not a valid URL", async () => {
      const response = await supertest(app)
        .post("/api/v1/emss/rexOverwrite")
        .set("emss-token", emssToken)
        .send({ ...validRexOverwrite, maestroEventUrl: "invalid-url" });
      expect(response.status).toBe(400);
      expect(response.body.message).toContain("MaestroEventURL be a valid URL");
    });

    describe("maestroActivityPropertiesByRefUuid validation", () => {
      test("Fails if invalid color", async () => {
        const payload = {
          ...validRexOverwrite,
          maestroActivityPropertiesByRefUuid: {
            egress: { color: "green", number: 1 },
          },
        };
        const response = await supertest(app)
          .post("/api/v1/emss/rexOverwrite")
          .set("emss-token", emssToken)
          .send(payload);
        expect(response.status).toBe(400);
        expect(response.body.message).toContain("maestroActivityPropertiesByRefUuid");
      });

      test("Fails if number length is greater than 3", async () => {
        const payload = {
          ...validRexOverwrite,
          maestroActivityPropertiesByRefUuid: {
            egress: { color: "#ffffff", number: "1011" },
          },
        };
        const response = await supertest(app)
          .post("/api/v1/emss/rexOverwrite")
          .set("emss-token", emssToken)
          .send(payload);
        expect(response.status).toBe(400);
        expect(response.body.message).toContain("Invalid number property");
      });
    });

    describe("stationEntriesByRefUuid validation", () => {
      test("Fails if invalid station refUuid", async () => {
        const payload = {
          ...validRexOverwrite,
          stationEntriesByRefUuid: { "invalid-uuid": { rexStatus: "complete" } },
        };
        const response = await supertest(app)
          .post("/api/v1/emss/rexOverwrite")
          .set("emss-token", emssToken)
          .send(payload);
        expect(response.status).toBe(400);
        expect(response.body.message).toContain("Invalid stationRefUuid");
      });

      test("Fails if stationEntriesByRefUuid contains invalid percent complete", async () => {
        const payload = {
          ...validRexOverwrite,
          stationEntriesByRefUuid: {
            [testStation.refUuid]: { rexStatus: "complete", maestroPercentCompleteEv1: 150 },
          },
        };
        const response = await supertest(app)
          .post("/api/v1/emss/rexOverwrite")
          .set("emss-token", emssToken)
          .send(payload);
        expect(response.status).toBe(400);
        expect(response.body.message).toContain(
          "Entry must have a valid maestroPercentCompleteEv1 property between 0 and 100."
        );
      });
    });

    describe("traverseEntriesByRefUuid validation", () => {
      test("Fails if invalid traverse refUuid", async () => {
        const payload = {
          ...validRexOverwrite,
          traverseEntriesByRefUuid: { "invalid-uuid": { rexStatus: "complete" } },
        };
        const response = await supertest(app)
          .post("/api/v1/emss/rexOverwrite")
          .set("emss-token", emssToken)
          .send(payload);
        expect(response.status).toBe(400);
        expect(response.body.message).toContain("Invalid traverseRefUuid");
      });

      test("Fails if traverseEntriesByRefUuid contains invalid percent complete", async () => {
        const payload = {
          ...validRexOverwrite,
          traverseEntriesByRefUuid: {
            [testTraverse.refUuid]: { rexStatus: "complete", maestroPercentCompleteEv2: -10 },
          },
        };
        const response = await supertest(app)
          .post("/api/v1/emss/rexOverwrite")
          .set("emss-token", emssToken)
          .send(payload);
        expect(response.status).toBe(400);
        expect(response.body.message).toContain(
          "Entry must have a valid maestroPercentCompleteEv2 property between 0 and 100."
        );
      });
    });

    describe("actionEntriesByRefUuid mass validation", () => {
      test("Fails if actionEntriesByRefUuid contains mass", async () => {
        const payload = {
          ...validRexOverwrite,
          actionEntriesByRefUuid: {
            [testStationAction.refUuid]: { rexStatus: "complete", mass: 1 },
          },
        };
        const response = await supertest(app)
          .post("/api/v1/emss/rexOverwrite")
          .set("emss-token", emssToken)
          .send(payload);
        expect(response.status).toBe(400);
        expect(response.body.message).toContain(
          "Action entry mass property should not be provided."
        );
      });
      test("Fails if actionEntriesByRefUuid contains mass = 0", async () => {
        const payload = {
          ...validRexOverwrite,
          actionEntriesByRefUuid: {
            [testStationAction.refUuid]: { rexStatus: "complete", mass: 0 },
          },
        };
        const response = await supertest(app)
          .post("/api/v1/emss/rexOverwrite")
          .set("emss-token", emssToken)
          .send(payload);
        expect(response.status).toBe(400);
        expect(response.body.message).toContain(
          "Action entry mass property should not be provided."
        );
      });
      test("Fails if actionEntriesByRefUuid contains mass is null", async () => {
        const payload = {
          ...validRexOverwrite,
          actionEntriesByRefUuid: {
            [testStationAction.refUuid]: { rexStatus: "complete", mass: null },
          } as ActionEntries,
        };
        const response = await supertest(app)
          .post("/api/v1/emss/rexOverwrite")
          .set("emss-token", emssToken)
          .send(payload);
        expect(response.status).toBe(400); // schema error
      });
      test("Fails if actionEntriesByRefUuid contains containerId > 20 characters", async () => {
        const payload = {
          ...validRexOverwrite,
          actionEntriesByRefUuid: {
            [testStationAction.refUuid]: {
              rexStatus: "complete",
              containerId: "a".repeat(21),
            },
          },
        };
        const response = await supertest(app)
          .post("/api/v1/emss/rexOverwrite")
          .set("emss-token", emssToken)
          .send(payload);
        expect(response.status).toBe(400);
        expect(response.body.message).toContain("containerId must be less than 20 characters.");
      });

      test("Fails if actionEntriesByRefUuid contains secondaryContainerId > 20 characters", async () => {
        const payload = {
          ...validRexOverwrite,
          actionEntriesByRefUuid: {
            [testStationAction.refUuid]: {
              rexStatus: "complete",
              secondaryContainerId: "a".repeat(21),
            },
          },
        };
        const response = await supertest(app)
          .post("/api/v1/emss/rexOverwrite")
          .set("emss-token", emssToken)
          .send(payload);
        expect(response.status).toBe(400);
        expect(response.body.message).toContain(
          "secondaryContainerId must be less than 20 characters."
        );
      });

      test("Fails if actionEntriesByRefUuid contains markerId > 20 characters", async () => {
        const payload = {
          ...validRexOverwrite,
          actionEntriesByRefUuid: {
            [testStationAction.refUuid]: {
              rexStatus: "complete",
              markerId: "a".repeat(21),
            },
          },
        };
        const response = await supertest(app)
          .post("/api/v1/emss/rexOverwrite")
          .set("emss-token", emssToken)
          .send(payload);
        expect(response.status).toBe(400);
        expect(response.body.message).toContain("markerId must be less than 20 characters.");
      });
    });

    test("Fails if xgressEntries contains invalid typeRefUuid", async () => {
      const payload = {
        ...validRexOverwrite,
        xgressEntries: { invalidType: { rexStatus: "complete" } },
      };
      const response = await supertest(app)
        .post("/api/v1/emss/rexOverwrite")
        .set("emss-token", emssToken)
        .send(payload);
      expect(response.status).toBe(400);
      expect(response.body.message).toContain(
        "Invalid typeRefUuid: invalidType for xgress. Must be 'egress' or 'ingress'."
      );
    });
  });

  describe("POST request - Business Logic", () => {
    test("Successfully updates REX with valid payload", async () => {
      const emitStoreUpsertSpy = vi.spyOn(SocketIo, "emitStoreUpsert");

      const response = await supertest(app)
        .post("/api/v1/emss/rexOverwrite")
        .set("emss-token", emssToken)
        .send(validRexOverwrite);
      expect(response.status).toBe(200);
      expect(response.body.status).toBe("success");
      expect(response.body.message).toContain("Rex updated for rex uuids");

      // Check that the array length is 2 (aka 2 rexes were sent because one was stopped)
      expect(response.body.data.length).toBe(2);
      const callArgs = emitStoreUpsertSpy.mock.calls[0][0]; // Get the first call's arguments
      expect(callArgs.data).toHaveLength(2);

      // Check updated rex
      const em = globalValues.orm.em.fork();
      const updatedRex = await em.findOne(Rex_db, { uuid: testRexes[0].uuid });
      expect(updatedRex).toBeDefined();
      expect(updatedRex.posEntries.length).toBe(3); // pos entries for each source should be created
      expect(updatedRex.posEntries[0].posTypeUuids.length).toBe(3); // each entry should include all pos types
    });
  });
});

afterAll(async () => {
  const em = globalValues.orm.em.fork();
  for (const rex of testRexes) {
    await em.nativeDelete(Rex_db, { uuid: rex.uuid });
  }
  await em.nativeDelete(Action_db, { uuid: testStationAction.uuid });
  await em.nativeDelete(Station_db, { uuid: testStation.uuid });
  await em.nativeDelete(Traverse_db, { uuid: testTraverse.uuid });
  await em.nativeDelete(Eva_db, { uuid: testEva.uuid });
  for (let i = 0; i < testAutomergeDocListings.length; i++) {
    await em.nativeDelete(Doc_Listing_db, { missionId: testAutomergeDocListings[i].missionId });
  }

  await globalValues.orm.close();
  globalValues.orm = null;
  vi.restoreAllMocks();
});
