// This file is for use with the vscode plugin, Simple REST Client
// (https://marketplace.visualstudio.com/items?itemName=Tino.simple-rest-client)
// With the plugin installed, click the "Send Request" text that appears above the `POST` entry below to hit local dev and test the endpoint.

GET http://localhost:4000/api/v1/maestro/v2/getMissions
Content-Type: application/json
emss-token: {{$dotenv EMSS_TOKEN}}
