stages:
  - stageless

  # This isn't used, but there are some tests within the FIT developer-ecosystem set that
  # expect to be run in the `test` stage. These tests are not run in this pipeline due to it not
  # having any of the requirements (e.g. Golang or PHP code). We could call them all out and specify
  # where they would run, or remove them, but it's easier to just make this unused "test".
  - test

default:
  artifacts:
    # Aggressively expire artifacts. The latest for any branch never expires
    expire_in: 1 day
  timeout: 10 minutes

variables:
  HOME: "/tmp" # required for openshift for now
  EMSS_DEPLOY_IMAGE: "$CI_REGISTRY/emss/docker-images:deploy-node-14-alpine"
  CURRENT_NODE_VERSION_IMAGE: "$CI_REGISTRY/emss/docker-images:node-18-alpine"
  # "Future" might be older if waiting on a newer version to come out
  FUTURE_NODE_VERSION_IMAGE: "$CI_REGISTRY/emss/docker-images:node-16-alpine"

  # Default image unless otherwise specified
image: "$CURRENT_NODE_VERSION_IMAGE"

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .next/cache/

# also run standard FIT dependency and package checks
# https://gitlab.fit.nasa.gov/developer-ecosystem/ci-job-templates
include:
  # Common jobs that basically all repos should run
  - project: "developer-ecosystem/ci-job-templates"
    ref: 3.3.0
    file: "/rollups/all-projects.gitlab-ci.yml"

  # Docker-in-Docker template for building docker images using docker runners
  - project: "developer-ecosystem/ci-job-templates"
    ref: 3.3.0
    file: "/extends/dind.gitlab-ci.yml"

  # A11y tests. Disabled for now.
  # - template: "Verify/Accessibility.gitlab-ci.yml"

# Overrride some properties on FIT jobs. Unfortunately using a template for these
# make GitLab angry, so a lot of repetition
project-check:
  stage: stageless
  needs: []
  tags: ["openshift"]
eslint-sast:
  stage: stageless
  needs: []
  tags: ["openshift"]
nodejs-scan-sast:
  stage: stageless
  needs: []
  tags: ["openshift"]
semgrep-sast:
  stage: stageless
  needs: []
  tags: ["openshift"]
sast:
  stage: stageless
  needs: []
  tags: ["openshift"]
secret_detection:
  stage: stageless
  needs: []
  tags: ["openshift"]
code-count:
  stage: stageless
  needs: []
  tags: ["openshift"]
# accessibility:
#   stage: stageless
#   needs: ["some deploy job or a running system in GitLab"]
#   tags: ["openshift"]

# manually overwrite the dependency-check to add our own suppression.xml
dependency-check:
  stage: stageless
  needs: ["install_dependencies"] # dependency-check takes a while, don't wait for "test" job
  tags: ["docker", "linux", "current"] # can't use openshift yet. "current" eliminates runner 2 which has been causing problems
  image:
    # Specify the Docker image to be used for the job, which is a customized image for running OWASP
    # dependency-check in a GitLab CI job
    name: $CI_REGISTRY/developer-ecosystem/dependency-check:latest
    # Entrypoint is overridden to allow a script to be run
    entrypoint: [""]
  script:
    # Run dependency-check from the location installed in the Docker container with the following arguments:
    # --scan "./"                                         Scans all files and folders within the working folder,
    #                                                     which contains the repository files as well as any
    #                                                     artifacts from prior jobs in the pipeline
    # --format ALL                                        Saves output in all formats so that HTML and JSON
    #                                                     files are available
    # --project "$CI_PROJECT_NAME"                        Use the GitLab project name, which is included in
    #                                                     the report
    # --failOnCVSS 0                                      Forces job to fail if any vulnerabilities are found
    # --suppression /suppressions/fp-cpe-suppression.xml  Suppress false positives where the dependency is
    #                                                     improperly identified
    # --suppression /suppressions/fp-cve-suppression.xml  Suppress false positives where the dependency is
    #                                                     properly identified, but the  CVE is a false positive
    - >
      /usr/share/dependency-check/bin/dependency-check.sh --scan "./"
      --format ALL
      --project "$CI_PROJECT_NAME"
      --failOnCVSS 0
      --suppression /suppressions/fp-cpe-suppression.xml
      --suppression /suppressions/fp-cve-suppression.xml
      --suppression ./.gitlab/dependency-check-suppression.xml

  # Allow failure will report a failure, but continue execution of the pipeline
  allow_failure: true
  artifacts:
    # Saving artifacts always forces them to be saved on failure as well as success
    when: always
    # Save the HTML and JSON formatted results as artifacts
    paths:
      - "./dependency-check-report.html"
      - "./dependency-check-report.json"

npm-audit:
  stage: stageless
  needs: []
  tags: ["openshift"]
  allow_failure: true
  script:
    - npm audit --json > npm-audit-report.json && echo "No vulnerabilities found" || npm audit
  artifacts:
    # Saving artifacts always forces them to be saved on failure as well as success
    when: always
    # Save the JSON formatted results as an artifact
    paths:
      - "./npm-audit-report.json"

install_dependencies:
  stage: stageless
  # This could be openshift, but it runs faster in a VM; other jobs rely on it, so get it done ASAP
  tags: ["docker", "linux", "current"]
  script:
    - npm ci
  artifacts:
    expire_in: 1 day
    paths:
      - ./node_modules/*

#
# Creates Software Bill of Materials
#
node-sbom:
  stage: stageless
  allow_failure: true
  tags: ["docker", "linux", "current"] # Can't be openshift due to it not pulling latest tag
  needs: ["install_dependencies"]
  image: $CI_REGISTRY/emss/docker-images:node-ci-sbom
  script:
    - /create-and-compare-bom.sh ./BOM.md
  artifacts:
    when: always
    paths:
      - "./bom.json"
      - "./new-bom.md"

# Template for `test` and `test-node-next` jobs, adding database service, etc.
.test_template:
  stage: stageless
  variables:
    POSTGRES_PORT: ${AEGIS_DB_PORT}
    POSTGRES_HOST: ${AEGIS_DB_HOST}
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_USER: ${AEGIS_DB_USER}
    POSTGRES_PASSWORD: ${AEGIS_DB_PASS}
    POSTGRES_DB: ${AEGIS_DB_NAME}
  services:
    # image should match database used in docker-compose.yml
    - name: postgis/postgis:14-3.2-alpine
      alias: postgres
  tags: ["docker", "linux", "current"]

test:
  extends: .test_template
  needs: ["install_dependencies"]
  script:
    - npm run migrate:up
    - npm run lint
    - npm run tsc
    - npm run test:coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: ./coverage/cobertura-coverage.xml
      junit:
        - junit.xml
    paths:
      - ./coverage/*

# test against next version of node that CODA may use, but allow to fail
test-node-next:
  image: "$FUTURE_NODE_VERSION_IMAGE"
  needs: ["install_dependencies"]
  extends: .test_template
  allow_failure: true
  script:
    - npm run migrate:up
    - npm run lint
    - npm run tsc
    - npm t

build:
  stage: stageless
  needs: ["install_dependencies"]

  # Could be openshift, but it runs faster in a VM; Since it's the longest-running job, run in VM.
  # If running with OpenShift, may need to set HOME to `/root` and use a didfferent container image.
  # See CODA and perhaps Maestro.
  tags: ["docker", "linux", "current"]
  script:
    # - sh ./.gitlab/create-fit-dotenv.sh fit
    - npm run build
  artifacts:
    paths:
      - .next
      - dist

# Sets up `IMAGE_NAME` environment variable to be used by docker build/push jobs
.docker_tag_template:
  stage: stageless
  timeout: 10 minutes
  retry: 2
  extends: .dind
  before_script:
    - TAG=${BUILD_IMAGE}
    - >
      if [ "${CI_COMMIT_REF_SLUG}" == "prod" ]; then
        TAG="${TAG}-prod"
      elif [ "${CI_COMMIT_REF_SLUG}" == "int" ]; then
        TAG="${TAG}-int"
      else
        TAG="${TAG}-dev"
      fi
    - IMAGE_NAME="${CI_REGISTRY_IMAGE}:${TAG}"

.docker_build_template:
  extends: .docker_tag_template
  script:
    - docker build --pull -t "${IMAGE_NAME}" -f ./docker/${BUILD_IMAGE}/Dockerfile --target ${BUILD_TARGET} .
    - mkdir builtimages
    - docker save "${IMAGE_NAME}" > builtimages/image.tar
  artifacts:
    paths:
      - builtimages

.docker_push_template:
  extends: .docker_tag_template
  script:
    - docker info
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker load -i builtimages/image.tar
    - docker push "${IMAGE_NAME}"

#
# Build docker images immediately (needs: [], meaning it has not prerequisites)
# so longer jobs get started soon. Don't push them until the docker:push:* jobs
# below, which wait for validation (unit testing, etc)
#
docker:build:nginx:
  extends: .docker_build_template
  needs: []
  variables:
    BUILD_IMAGE: nginx
    BUILD_TARGET: base

docker:build:nextjs:
  extends: .docker_build_template
  needs: []
  variables:
    BUILD_IMAGE: nextjs
    BUILD_TARGET: prod

#
# Push docker images after necessary jobs pass (e.g. unit testing passes)
#
docker:push:nginx:
  extends: .docker_push_template
  needs:
    - job: build
      artifacts: false
    - job: test
      artifacts: false
    - docker:build:nginx
  variables:
    BUILD_IMAGE: nginx

docker:push:nextjs:
  extends: .docker_push_template
  needs:
    - job: build
      artifacts: false
    - job: test
      artifacts: false
    - docker:build:nextjs
  variables:
    BUILD_IMAGE: nextjs

make-dotenv:
  stage: stageless
  needs:
    - docker:push:nginx
    - docker:push:nextjs
  script:
    # Baseline .env from CI/CD file-variable
    - cp "${FIT_DOTENV_FILE_PATH}" ./.env

    # Determine which docker image type (dev, int, or prod) to deploy based on branch
    - >
      if [ "${CI_COMMIT_REF_SLUG}" == "prod" ]; then
        DEPLOY_ENV="prod"
      elif [ "${CI_COMMIT_REF_SLUG}" == "int" ]; then
        DEPLOY_ENV="int"
      else
        DEPLOY_ENV="dev"
      fi

    # Append desired docker images (dev, int, or prod) to
    - echo "" >> ./.env
    - echo "DOCKER_IMAGE_NGINX=eegitlabregistry.fit.nasa.gov/emss/aegis:nginx-${DEPLOY_ENV}" >> ./.env
    - echo "DOCKER_IMAGE_NEXTJS=eegitlabregistry.fit.nasa.gov/emss/aegis:nextjs-${DEPLOY_ENV}" >> ./.env

  # All this job does is prepare artifacts to be exported to the deploy jobs
  artifacts:
    paths:
      - .env
      - .fitdock.yml
      - docker-compose.yml

.deploy-template:
  stage: stageless
  timeout: 10 minutes
  variables:
    GIT_STRATEGY: none # Don't checkout the repo, just get artifacts

  script:
    # Ultimately it'd be good to have as much of the following wrapped up in a job template
    # that multiple projects could share. One problem may be getting the sudo password session
    # to be transferrable between before_script (in a template) and script. Then again, the docs
    # say: "Scripts you specify in before_script are concatenated with any scripts you specify
    # in the main script. The combined scripts execute together in a single shell."

    - echo "${DEPLOY_SUDO_PASS}" | sudo -S touch /tmp/somefile

    # Ultimately get this from .fitdock.yml, but need to write a method to do that
    - export INSTALL_DIR=/opt/aegis

    - >
      if ! sudo fitdock --version; then
        sudo git clone -b fitdock https://gitlab.fit.nasa.gov/fitbox/fitbox.git /opt/fitdock
        sudo bash /opt/fitdock/src/scripts/setup-ubuntu.sh
      fi

    - >
      if [[ "${CI_COMMIT_TITLE}" =~ \[fitdock\] ]] || ! cmp --silent ./.fitdock.yml "${INSTALL_DIR}/.fitdock.yml"; then
        echo "do deploy";
        sudo mkdir -p "${INSTALL_DIR}"
        sudo chown gitlab-runner:gitlab-runner "${INSTALL_DIR}"
        /bin/cp -f ./.fitdock.yml "${INSTALL_DIR}/.fitdock.yml"
        sudo fitdock "${INSTALL_DIR}/.fitdock.yml"
      fi

    # Move into place
    # /bin/cp to avoid aliased version of `cp` which doesn't allow forcing with -f
    - /bin/cp -f ./.env "${INSTALL_DIR}/.env"
    - /bin/cp -f ./docker-compose.yml "${INSTALL_DIR}/docker-compose.yml"
    - rm -f .env
    - rm -f .fitdock.yml
    - rm -f docker-compose.yml

    # Take docker-compose down, pull latest, bring it back up
    - cd "${INSTALL_DIR}"
    - echo $CI_JOB_TOKEN | sudo /usr/bin/docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

    # Get the latest of each image
    - sudo /usr/bin/docker compose pull

    # Using the new images, re-up Compose. Also remove anything no longer defined in
    # docker-compose.yml via --remove-orphans
    - sudo /usr/bin/docker compose up -d --remove-orphans

    # remove any images no longer in use
    - sudo /usr/bin/docker image prune -af

deploy:dev1:
  extends: .deploy-template
  tags: ["emss-aegis-dev1"]
  needs: ["make-dotenv"]
  environment:
    name: development1
    url: https://aegis-dev1.fit.nasa.gov
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_DEV1
  when: manual

deploy:int:
  extends: .deploy-template
  tags: ["emss-aegis-int"]
  needs: ["make-dotenv"]
  environment:
    name: integration
    url: https://aegis-int.fit.nasa.gov
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_INT
  only:
    - int

deploy:prod:
  extends: .deploy-template
  tags: ["emss-aegis-prod"]
  needs: ["make-dotenv"]
  environment:
    name: production
    url: https://aegis.fit.nasa.gov
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_PROD
  when: manual
  only:
    - prod

dev1-nuke-db:
  tags: ["emss-aegis-dev1"]
  needs: []
  environment:
    name: development1
    url: https://aegis-dev1.fit.nasa.gov
  when: manual
  stage: stageless
  timeout: 10 minutes
  variables:
    GIT_STRATEGY: none
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_DEV1
  script:
    # init sudo ability
    - echo "${DEPLOY_SUDO_PASS}" | sudo -S touch /tmp/somefile

    - cd /opt/aegis
    - sudo /usr/bin/docker compose down --remove-orphans
    - sudo rm -rf /d1/postgres
    - sudo /usr/bin/docker compose up -d
    - docker compose exec nextjs npm run migrate:up

dev1-seed-db:
  tags: ["emss-aegis-dev1"]
  needs: []
  environment:
    name: development1
    url: https://aegis-dev1.fit.nasa.gov
  when: manual
  stage: stageless
  timeout: 10 minutes
  variables:
    GIT_STRATEGY: none

  script:
    - cd /opt/aegis
    # wipe all tables, run all migrations, run the seeder
    - docker compose exec nextjs npm run seed
