version: "3"
services:
  node:
    image: node:16
    container_name: aegis_node
    tty: true
    user: "node"
    command: bash -c "npm install && npm run build && npm run start"
    restart: always
    build: ./
    working_dir: /app
    stdin_open: true
    hostname: aegis-local.fit.nasa.gov
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    networks:
      - aegis-network
  postgis:
    image: postgis/postgis:14-3.2-alpine
    container_name: aegis_postgis
    restart: always
    tty: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postagresgetthemess
      POSTGRES_DB: aegis
    volumes:
      - ./:/app
      - ./.docker/mmgis.sql:/docker-entrypoint-initdb.d/mmgis.sql
    networks:
      - aegis-network

#Docker Networks
networks:
  aegis-network:
    driver: bridge