#
# DOCKER OVERRIDE FILE:
# This is an override file. It is intended to be used on top of the base docker-compose.yml file.
#
# SUMMARY:
# 1. Rather than pull images from a container registry as done in the main docker-compose.yml,
#    instead build the images locally
# 2. Add code directory on the host machine via a volume
#
version: "3.9"
services:
  nginx:
    # In dev, don't pull an image from container registry: build it locally from a Dockerfile.
    image: aegis-dev-nginx:latest
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      target: dev
    volumes:
      - ./docker/nginx/nginx-dev.conf:/etc/nginx/nginx.conf:ro

  apiv1:
    # See comment above regarding `image`/`build` overrides
    image: aegis-dev-apiv1:latest
    build:
      context: .
      dockerfile: ./docker/apiv1/Dockerfile
      target: dev
    ports:
      # API v1 is hard-coded to run on 3000 in docker, and nginx proxies it. Hard-coding this and
      # not making it configurable keeps docker config simpler.
      - "3000:3000"

      # This is what is in place for Next.JS. Use another port for this container?
      # VS Code debug port. This isn't needed in production, and won't be exposed by FIT servers,
      # but is simpler config-wise to put here versus in the overrides file
      # - "9229:9229"
    volumes:
      # In dev we want the host's code to be present on the container
      - .:/src

      # Create volume for node_modules that masks the node_modules directory volumed-in by the
      # `./:/app` volume. We don't want to use the host's node_modules, since it'll be constructed
      # for the host's OS. We want a node_modules set up for this container's OS.
      - container_only_node_modules:/src/node_modules

  database:
    ports:
      # For local dev, expose the database outside the docker network in case devs want to use
      # a SQL client on their machine (e.g. HeidiSQL, etc)
      - "5432:5432"

  gdal:
    # See comment above regarding `image`/`build` overrides
    image: aegis-dev-gdal:latest
    build:
      context: .
      dockerfile: ./docker/gdal/Dockerfile
      target: base
    volumes:
      - ./src/server/python:/app
    ports:
      - "${GDAL_PORT}:80"
      - 5678:5678

  vitedev:
    container_name: aegis-vitedev-1
    image: aegis-vitedev-1:latest
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      # Override what is in .env (which may be "localhost" to support native local dev) such
      # that it is always "database" in a full Docker-Compose setup.
      - AEGIS_DB_HOST=database
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    build:
      context: .
      dockerfile: ./docker/vitedev/Dockerfile
      target: base

volumes:
  container_only_node_modules:
