version: "3.9"
services:
  nginx:
    container_name: aegis-nginx-1
    image: ${DOCKER_IMAGE_NGINX}
    restart: unless-stopped
    depends_on:
      - apiv1
    volumes:
      - ${STATIC_DIR}:/usr/share/nginx/html/static:ro
      - ${DOCKER_SSL_CERTS_DIR}:/etc/pki/tls/certs
      - ${DOCKER_SSL_PRIVATE_DIR}:/etc/pki/tls/private

    ports:
      # AEGIS requires launchpad, so must be over HTTPS and not have a port specified in the URL
      # e.g. https://aegis.fit.nasa.gov not https://aegis.fit.nasa.gov:8000
      - "443:443"

  apiv1:
    container_name: aegis-apiv1-1
    image: ${DOCKER_IMAGE_APIV1}
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      # Override what is in .env (which may be "localhost" to support native local dev) such
      # that it is always "database" in a full Docker-Compose setup.
      - AEGIS_DB_HOST=database
    volumes:
      - ${STATIC_DIR}:/${STATIC_DIR}

  database:
    container_name: aegis-database-1
    image: postgis/postgis:14-3.2-alpine
    # image: postgres:14.12-alpine # pending EMSS/docker-images MR !36
    restart: unless-stopped
    environment:
      # Used for setting up a DB for the first time. These are not stored in the container
      # but rather in the db data itself
      POSTGRES_PASSWORD: ${AEGIS_DB_PASS}
      POSTGRES_DB: ${AEGIS_DB_NAME}
    healthcheck:
      test: "pg_isready -U postgres && psql --username=postgres --list && psql --username=postgres ${AEGIS_DB_NAME} -c 'SELECT id FROM Mission_db LIMIT 1'"
      interval: 30s # how often to check health
      timeout: 5s # fail if it takes longer than this
      retries: 6 # max consecutive failures
      start_period: 15s # db takes about 20 seconds to come up
    volumes:
      # map the DB data to be stored outside the container
      - ${DOCKER_DB_DATA_DIR}:/var/lib/postgresql/data
      - ${DOCKER_DB_INIT_DIR}:/docker-entrypoint-initdb.d

  gdal:
    container_name: aegis-gdal-1
    image: ${DOCKER_IMAGE_GDAL}
    restart: unless-stopped
    volumes:
      - ${STATIC_DIR}:/static
