version: "3"
services:
  node:
    image: node:16
    container_name: aegis_node
    tty: true
    user: "node"
    command: bash -c "npm install && npm run dev"
    working_dir: /app
    stdin_open: true
    hostname: aegis-local.fit.nasa.gov
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    networks:
      - aegis-network
  postgres:
    image: postgres:14.4-alpine
    container_name: aegis_postgres
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: posty
      POSTGRES_PASSWORD: postagresgetthemess
      POSTGRES_DB: aegis
    volumes:
      - ./:/app
    networks:
      - aegis-network
  postgis:
    image: postgis/postgis:14-3.2-alpine
    container_name: aegis_postgis

#Docker Networks
networks:
  aegis-network:
    driver: bridge