#
# DOCKER OVERRIDE FILE:
# This is an override file. It is intended to be used on top of the base docker-compose.yml file.
#
# SUMMARY:
# Do the exact same thing as the production `docker-compose.yml`, just build locally as a way to
# quickly preview what a production build would do.
#
version: '3.9'
services:
  nginx:
    image: aegis-preview-nginx:latest
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile

  nextjs:
    image: aegis-preview-nextjs:latest
    build:
      context: .
      dockerfile: ./docker/nextjs/Dockerfile
      target: prod

  gdal:
    image: aegis-preview-gdal:latest
    build:
      context: .
      dockerfile: ./docker/gdal/Dockerfile
