version: "3"
services:
  nginx:
    image: nginx:1.23.1-alpine
    container_name: aegis_web
    restart: unless-stopped
    volumes:
      - ./.docker/nginx:/etc/nginx/conf.d
      - /var/www/:/var/www/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - aegis-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  node:
    image: node:16
    container_name: aegis_node
    tty: true
    user: "node"
    command: bash -c "npm install && exit"
    working_dir: /app
    stdin_open: true
    hostname: aegis-local.fit.nasa.gov
    ports:
      - "4000:4000"
      - "9229:9229"
    volumes:
      - ./:/app
    networks:
      - aegis-network
  postgis:
    image: postgis/postgis:14-3.2-alpine
    container_name: aegis_postgis
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/app
      - ./.docker/mmgis.sql:/docker-entrypoint-initdb.d/mmgis.sql
    networks:
      - aegis-network
#Docker Networks
networks:
  aegis-network:
    driver: bridge
