#
# DOCKER OVERRIDE FILE:
# This is an override file. It is intended to be used on top of the base docker-compose.yml file.
#
# SUMMARY:
# Do the exact same thing as the production `docker-compose.yml`, just build locally as a way to
# quickly preview what a production build would do.
# Don't pull an image from container registry: build it locally from a Dockerfile.
#
version: "3.9"
services:
  nginx:
    image: aegis-preview-nginx:latest
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      target: prod

  apiv1:
    image: aegis-preview-apiv1:latest
    build:
      context: .
      dockerfile: ./docker/apiv1/Dockerfile
      target: prod
    environment:
      # Override what is in .env (which may be "localhost" to support native local dev) such
      # that it is always "database" in a full Docker-Compose setup.
      - AEGIS_DB_HOST=database


  gdal:
    image: aegis-preview-gdal:latest
    build:
      context: .
      dockerfile: ./docker/gdal/Dockerfile
      target: base
