import type { EntityManager } from "@mikro-orm/core";
import { Seeder } from "@mikro-orm/seeder";
import { PermissionRole, User } from "../models/user.model";
import { Mission } from "../models/mission.model";

export class DatabaseSeeder extends Seeder {
  async run(em: EntityManager): Promise<void> {
    em.create(User, {
      username: "admin",
      password: "admin",
      permission: PermissionRole.ADMIN,
      email: "admin@nasa.gov",
    });
    em.create(Mission, {
      mission: "Apollo_14",
      config: {
        msv: {
          mission: "Apollo_14",
          site: "",
          masterdb: false,
          view: ["-3.64602", "-17.47204", "14"],
          radius: { major: "1737400", minor: "1737400" },
          mapscale: "",
        },
        projection: {
          custom: false,
          epsg: "EPSG:3857",
          proj: "+proj=merc +a=1737400 +b=1737400 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs",
          xmlpath: "",
          bounds: [
            "-17.52833106710000",
            "-3.91299838779177",
            "-17.38598938443003",
            "-2.96327743284100",
          ],
          origin: ["-17.52833106710000", "-3.91299838779177"],
          reszoomlevel: 8,
          resunitsperpixel: 611.49622617187504,
        },
        look: {
          pagename: "postgres",
          minimalist: false,
          zoomcontrol: true,
          graticule: false,
          coordll: true,
          coorden: true,
          coordrxy: true,
          coordsite: false,
          coordelev: false,
          coordelevurl: "",
          coordlngoffset: "",
          coordlatoffset: "",
          coordeastoffset: "",
          coordnorthoffset: "",
          coordeastmult: "",
          coordnorthmult: "",
          primarycolor: "",
          secondarycolor: "",
          tertiarycolor: "",
          accentcolor: "",
          bodycolor: "",
          topbarcolor: "",
          toolbarcolor: "",
          mapcolor: "",
          highlightcolor: "",
          copylink: true,
          screenshot: true,
          fullscreen: true,
          help: true,
          logourl: "",
          helpurl: "",
        },
        panels: ["viewer", "map", "globe"],
        panelSettings: { demFallbackPath: "", demFallbackFormat: null, demFallbackType: null },
        tools: [
          { name: "Layers", icon: "buffer", js: "LayersTool" },
          { name: "Legend", icon: "format-list-bulleted-type", js: "LegendTool" },
          { name: "Info", icon: "information-variant", js: "InfoTool" },
          {
            name: "Sites",
            icon: "pin",
            js: "SitesTool",
            variables: {
              sites: [{ name: "Landing Site", code: "LS", view: [-3.64602, -17.47204, 14] }],
            },
          },
          {
            name: "Isochrone",
            icon: "circle-double",
            js: "IsochroneTool",
            variables: {
              data: {
                DEM: [
                  {
                    name: "NAC Ortho 50cm M150633128",
                    tileurl: "Layers/NAC_ortho_50cm_1_v4/{z}/{x}/{y}.png",
                    minZoom: 8,
                    maxNativeZoom: 18,
                    resolution: 256,
                    interpolateSeams: true,
                  },
                ],
                slope: [{ "...": "..." }],
                cost: [{ "...": "..." }],
              },
              interpolateSeams: false,
              models: ["Traverse Time", "Isodistance", "..."],
            },
          },
          { name: "Chemistry", icon: "flask", js: "ChemistryTool" },
          { name: "Draw", icon: "lead-pencil", js: "DrawTool" },
          {
            name: "Identifier",
            icon: "map-marker",
            js: "IdentifierTool",
            variables: { tile_with_DEM: { url: "Data/missionDEM.tif", unit: "m" } },
          },
          {
            name: "Measure",
            icon: "chart-areaspline",
            js: "MeasureTool",
            variables: { dem: "Data/missionDEM.tif" },
          },
        ],
        layers: [
          {
            name: "Traverses",
            type: "header",
            demparser: "",
            controlled: false,
            tileformat: "tms",
            initialOpacity: 1,
            time: {
              enabled: false,
              type: "global",
              isRelative: true,
              current: new Date("2022-05-17T18:39:14Z"),
              start: "",
              end: "",
              format: "%Y-%m-%dT%H:%M:%SZ",
              refresh: "1 hours",
              increment: "5 minutes",
            },
            shape: "none",
            sublayers: [
              {
                name: "Apollo 14 Traverse",
                kind: "none",
                type: "vector",
                url: "Data/Apollo14Traverse.geojson",
                demparser: "",
                controlled: false,
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                style: {
                  className: "apollo14traverse",
                  color: "#0075c0",
                  fillColor: "#0075c0",
                  weight: 1,
                  fillOpacity: 1,
                  opacity: 1,
                },
                variables: { useKeyAsName: "Shape_Leng" },
                radius: 1,
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-05-17T18:39:14Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
            ],
          },
          {
            name: "Sample Stations",
            type: "header",
            demparser: "",
            controlled: false,
            tileformat: "tms",
            initialOpacity: 1,
            time: {
              enabled: false,
              type: "global",
              isRelative: true,
              current: new Date("2022-05-17T18:39:14Z"),
              start: "",
              end: "",
              format: "%Y-%m-%dT%H:%M:%SZ",
              refresh: "1 hours",
              increment: "5 minutes",
            },
            shape: "none",
            sublayers: [
              {
                name: "Apollo 14 Sample Stations",
                kind: "none",
                type: "vector",
                url: "Data/Apollo14.geojson",
                demparser: "",
                controlled: false,
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                style: {
                  className: "apollo14samplestations",
                  color: "#0075c0",
                  fillColor: "#0075c0",
                  weight: 1,
                  fillOpacity: 1,
                  opacity: 1,
                },
                variables: { useKeyAsName: "Name" },
                radius: 4,
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-05-17T18:39:14Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
            ],
          },
          {
            name: "Detrended Roughness",
            type: "header",
            demparser: "",
            controlled: false,
            tileformat: "tms",
            initialOpacity: 1,
            time: {
              enabled: false,
              type: "global",
              isRelative: true,
              current: new Date("2022-05-17T18:39:14Z"),
              start: "",
              end: "",
              format: "%Y-%m-%dT%H:%M:%SZ",
              refresh: "1 hours",
              increment: "5 minutes",
            },
            shape: "none",
            sublayers: [
              {
                name: "NAC DTM DTR 2m ",
                type: "tile",
                url: "Layers/NAC_DTM_DTR_2m/{z}/{x}/{y}.png",
                demtileurl: "Layers/NAC_DTM_2m_v2/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 8,
                maxNativeZoom: 14,
                maxZoom: 23,
                boundingBox: [
                  -17.52243003485202, -3.90650040991372, -17.39118264564012, -2.96897224131543,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-05-17T18:39:14Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
            ],
          },
          {
            name: "Confidence Map",
            type: "header",
            demparser: "",
            controlled: false,
            tileformat: "tms",
            initialOpacity: 1,
            time: {
              enabled: false,
              type: "global",
              isRelative: true,
              current: new Date("2022-05-17T18:39:14Z"),
              start: "",
              end: "",
              format: "%Y-%m-%dT%H:%M:%SZ",
              refresh: "1 hours",
              increment: "5 minutes",
            },
            shape: "none",
            sublayers: [
              {
                name: "NAC DTM 2m Confidence Map",
                type: "tile",
                url: "Layers/NAC_DTM_2m_confidence_map/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 8,
                maxNativeZoom: 14,
                maxZoom: 23,
                boundingBox: [
                  -17.52838060176, -3.91301487948368, -17.38598936240026, -2.96326094389799,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-05-17T18:39:14Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
            ],
          },
          {
            name: "Hillshade",
            type: "header",
            demparser: "",
            controlled: false,
            tileformat: "tms",
            initialOpacity: 1,
            time: {
              enabled: false,
              type: "global",
              isRelative: true,
              current: new Date("2022-05-17T18:39:14Z"),
              start: "",
              end: "",
              format: "%Y-%m-%dT%H:%M:%SZ",
              refresh: "1 hours",
              increment: "5 minutes",
            },
            shape: "none",
            sublayers: [
              {
                name: "NAC DTM 2m Hillshade",
                type: "tile",
                url: "Layers/NAC_DTM_hillshade/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 8,
                maxNativeZoom: 14,
                maxZoom: 23,
                boundingBox: [
                  -17.52838060176, -3.91301487948368, -17.38598936240026, -2.96326094389799,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-05-17T18:39:14Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
            ],
          },
          {
            name: "Basemaps",
            type: "header",
            demparser: "",
            controlled: false,
            tileformat: "tms",
            initialOpacity: 1,
            time: {
              enabled: false,
              type: "global",
              isRelative: true,
              current: new Date("2022-05-17T18:39:14Z"),
              start: "",
              end: "",
              format: "%Y-%m-%dT%H:%M:%SZ",
              refresh: "1 hours",
              increment: "5 minutes",
            },
            shape: "none",
            sublayers: [
              {
                name: "NAC Ortho 50cm M150639913",
                type: "tile",
                url: "Layers/NAC_ortho_50cm_2/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 8,
                maxNativeZoom: 16,
                maxZoom: 23,
                boundingBox: [
                  -17.5283310671, -3.91299838779177, -17.38598938443003, -2.963277432841,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-05-17T18:39:14Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "NAC Ortho 50cm M150633128",
                type: "tile",
                url: "Layers/NAC_ortho_50cm_1_v4/{z}/{x}/{y}.png",
                demtileurl: "Layers/NAC_DTM_2m_v2/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                tileformat: "tms",
                visibility: true,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 8,
                maxNativeZoom: 16,
                maxZoom: 23,
                boundingBox: [
                  -17.52243003485202, -3.90647227279352, -17.39118427681328, -2.96897224131543,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-05-17T18:39:14Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
            ],
          },
        ],
        time: { enabled: false, visible: false, format: "" },
      },
      version: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
    em.create(Mission, {
      mission: "Potrillo_VF_v001",
      config: {
        msv: {
          mission: "Potrillo_VF_v001",
          site: "",
          masterdb: false,
          view: ["31.970525", "-106.963026", "11"],
          radius: { major: "6378137", minor: "6378137" },
          mapscale: "",
        },
        projection: {
          custom: false,
          epsg: "",
          proj: "",
          xmlpath: "",
          bounds: [
            "-107.47297700557911",
            "31.65986801717055",
            "-106.55954285121517",
            "32.28391307648736",
          ],
          origin: ["-107.47297700557911", "31.65986801717055"],
          reszoomlevel: 8,
          resunitsperpixel: 611.49622617187504,
        },
        look: {
          pagename: "postgres",
          minimalist: false,
          zoomcontrol: true,
          graticule: false,
          coordll: true,
          coorden: true,
          coordrxy: true,
          coordsite: false,
          coordelev: false,
          coordelevurl: "",
          coordlngoffset: "",
          coordlatoffset: "",
          coordeastoffset: "",
          coordnorthoffset: "",
          coordeastmult: "",
          coordnorthmult: "",
          primarycolor: "",
          secondarycolor: "",
          tertiarycolor: "#ffffff",
          accentcolor: "#B2DFDB",
          bodycolor: "",
          topbarcolor: "#00796B",
          toolbarcolor: "#009688",
          mapcolor: "",
          highlightcolor: "",
          copylink: true,
          screenshot: true,
          fullscreen: true,
          help: true,
          logourl: "",
          helpurl: "",
        },
        panels: ["viewer", "map", "globe"],
        panelSettings: { demFallbackPath: "", demFallbackFormat: null, demFallbackType: null },
        tools: [
          { name: "Layers", icon: "buffer", js: "LayersTool" },
          { name: "Legend", icon: "format-list-bulleted-type", js: "LegendTool" },
          { name: "Info", icon: "information-variant", js: "InfoTool" },
          {
            name: "Sites",
            icon: "pin",
            js: "SitesTool",
            variables: {
              sites: [{ name: "Site1", code: "S1", view: [31.970525, -106.963026, 14] }],
            },
          },
          {
            name: "Isochrone",
            icon: "circle-double",
            js: "IsochroneTool",
            variables: {
              data: {
                DEM: [
                  {
                    name: "DEM",
                    tileurl: "Layers/portrillo_DEM/{z}/{x}/{y}.png",
                    minZoom: 0,
                    maxNativeZoom: 17,
                    resolution: 32,
                    interpolateSeams: true,
                  },
                ],
              },
              models: ["Traverse Time", "Isodistance"],
            },
          },
          {
            name: "Viewshed",
            icon: "wifi-strength-2",
            js: "ViewshedTool",
            variables: {
              data: [
                {
                  name: "DEM",
                  demtileurl: "Layers/portrillo_DEM/{z}/{x}/{y}.png",
                  minZoom: 0,
                  maxNativeZoom: 17,
                },
              ],
            },
          },
          { name: "Draw", icon: "lead-pencil", js: "DrawTool" },
          {
            name: "Identifier",
            icon: "map-marker",
            js: "IdentifierTool",
            variables: { tile_with_DEM: { url: "Data/missionDEM.tif", unit: "m" } },
          },
          {
            name: "Measure",
            icon: "chart-areaspline",
            js: "MeasureTool",
            variables: { dem: "Data/3DEP_DEM_10M/kilbournehole_10m_dem_3857.tif" },
          },
        ],
        layers: [
          {
            name: "Contours",
            type: "header",
            demparser: "",
            controlled: false,
            tileformat: "tms",
            initialOpacity: 1,
            time: {
              enabled: false,
              type: "global",
              isRelative: true,
              current: new Date("2022-04-19T13:44:22Z"),
              start: "",
              end: "",
              format: "%Y-%m-%dT%H:%M:%SZ",
              refresh: "1 hours",
              increment: "5 minutes",
            },
            shape: "none",
            sublayers: [
              {
                name: "Contours 10m",
                kind: "none",
                type: "vector",
                url: "Layers/Portrillo_Contours/Portrillo_10m_contours_4326.geojson",
                demparser: "",
                controlled: false,
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                style: {
                  className: "contours10m",
                  color: "#F0FFFF",
                  fillColor: "undefined",
                  weight: 1,
                  fillOpacity: null,
                  opacity: 1,
                },
                variables: { useKeyAsName: "ELEV" },
                radius: 1,
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "Contours 50m",
                kind: "none",
                type: "vector",
                url: "Layers/Portrillo_Contours/Portrillo_50m_contours_4326.geojson",
                demparser: "",
                controlled: false,
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                style: {
                  className: "contours50m",
                  color: "#32CD32",
                  fillColor: "undefined",
                  weight: 1,
                  fillOpacity: null,
                  opacity: 1,
                },
                variables: { useKeyAsName: "ELEV" },
                radius: 1,
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
            ],
          },
          {
            name: "Terrain Ruggedness",
            type: "header",
            demparser: "",
            controlled: false,
            tileformat: "tms",
            initialOpacity: 1,
            time: {
              enabled: false,
              type: "global",
              isRelative: true,
              current: new Date("2022-04-19T13:44:22Z"),
              start: "",
              end: "",
              format: "%Y-%m-%dT%H:%M:%SZ",
              refresh: "1 hours",
              increment: "5 minutes",
            },
            shape: "none",
            sublayers: [
              {
                name: "TRI Regional 10m",
                type: "tile",
                url: "Layers/portrillo_TRI/{z}/{x}/{y}.png",
                demtileurl: "Layers/portrillo_DEM/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                legend: "Layers/portrillo_TRI/portrillo_tri.csv",
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 9,
                maxNativeZoom: 13,
                maxZoom: 23,
                boundingBox: [
                  -107.44123839383117, 31.78402949781903, -106.79654100895651, 32.25249202592094,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "TRI Regional 50m",
                type: "tile",
                url: "Layers/portrillo_TRI_50m/{z}/{x}/{y}.png",
                demtileurl: "Layers/portrillo_DEM/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                legend: "Layers/portrillo_TRI/portrillo_tri.csv",
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 9,
                maxNativeZoom: 11,
                maxZoom: 23,
                boundingBox: [
                  -107.44123839383117, 31.78407183033917, -106.79669717747541, 32.25249202592094,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "TRI 1m Hunts Hole",
                type: "tile",
                url: "Layers/HuntsHole_TRI/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 14,
                maxNativeZoom: 17,
                maxZoom: 23,
                boundingBox: [
                  -106.97889305670077, 31.92641529168681, -106.96381932623324, 31.93993972184672,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "TRI 1m Kilbourne North Rim",
                type: "tile",
                url: "Layers/NorthRim_TRI/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                legend: "Layers/portrillo_TRI/portrillo_tri.csv",
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 14,
                maxNativeZoom: 17,
                maxZoom: 23,
                boundingBox: [
                  -106.9709488315368, 31.97811367853517, -106.95093436700662, 31.99308568520568,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "TRI 1m Kilbourne South Rim",
                type: "tile",
                url: "Layers/SouthRim_TRI/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                legend: "Layers/portrillo_TRI/portrillo_tri.csv",
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 14,
                maxNativeZoom: 17,
                maxZoom: 23,
                boundingBox: [
                  -106.96188443236635, 31.95245212214806, -106.94899360803925, 31.96466952541393,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "TRI 1m Kilbourne Southwest Rim",
                type: "tile",
                url: "Layers/SouthwestRim_TRI/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                legend: "Layers/portrillo_TRI/portrillo_tri.csv",
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 15,
                maxNativeZoom: 17,
                maxZoom: 23,
                boundingBox: [
                  -106.9783220884045, 31.95579631978293, -106.96773470346767, 31.96242471126321,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "TRI 20cm Kilbourne Southwest Rim",
                type: "tile",
                url: "Layers/SouthwestRim_20cm_TRI/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                legend: "Layers/portrillo_TRI/portrillo_tri.csv",
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 15,
                maxNativeZoom: 19,
                maxZoom: 23,
                boundingBox: [
                  -106.9783220884045, 31.95579430955042, -106.96773434503986, 31.96242471583598,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
            ],
          },
          {
            name: "Aspect",
            type: "header",
            demparser: "",
            controlled: false,
            tileformat: "tms",
            initialOpacity: 1,
            time: {
              enabled: false,
              type: "global",
              isRelative: true,
              current: new Date("2022-04-19T13:44:22Z"),
              start: "",
              end: "",
              format: "%Y-%m-%dT%H:%M:%SZ",
              refresh: "1 hours",
              increment: "5 minutes",
            },
            shape: "none",
            sublayers: [
              {
                name: "Aspect 10m Regional",
                type: "tile",
                url: "Layers/portrillo_aspect/{z}/{x}/{y}.png",
                demtileurl: "Layers/portrillo_DEM/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                legend: "Layers/portrillo_aspect/portrillo_aspect_legend.csv",
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 9,
                maxNativeZoom: 13,
                maxZoom: 23,
                boundingBox: [
                  -107.44123839383117, 31.78402949781903, -106.79654100895651, 32.25249202592094,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "Aspect 1m Hunts Hole",
                type: "tile",
                url: "Layers/HuntsHole_Aspect/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                legend: "Layers/portrillo_aspect/portrillo_aspect_legend.csv",
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 14,
                maxNativeZoom: 17,
                maxZoom: 23,
                boundingBox: [
                  -106.97889305670077, 31.92641529168681, -106.96381932623324, 31.93993972184672,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "Aspect 1m Kilbourne North Rim",
                type: "tile",
                url: "Layers/NorthRim_Aspect/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                legend: "Layers/portrillo_aspect/portrillo_aspect_legend.csv",
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 14,
                maxNativeZoom: 17,
                maxZoom: 23,
                boundingBox: [
                  -106.9709488315368, 31.97811367853517, -106.95093436700662, 31.99308568520568,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "Aspect 1m Kilbourne South Rim",
                type: "tile",
                url: "Layers/SouthRim_Aspect/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                legend: "Layers/portrillo_aspect/portrillo_aspect_legend.csv",
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 14,
                maxNativeZoom: 17,
                maxZoom: 23,
                boundingBox: [
                  -106.96188443236635, 31.95245212214806, -106.94899360803925, 31.96466952541393,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "Aspect 1m Kilbourne Southwest Rim",
                type: "tile",
                url: "Layers/SouthwestRim_Aspect/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                legend: "Layers/portrillo_aspect/portrillo_aspect_legend.csv",
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 15,
                maxNativeZoom: 17,
                maxZoom: 23,
                boundingBox: [
                  -106.9783220884045, 31.95579631978293, -106.96773470346767, 31.96242471126321,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "Aspect 20cm Kilbourne Southwest Rim",
                type: "tile",
                url: "Layers/SouthwestRim_20cm_Aspect/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                legend: "Layers/portrillo_aspect/portrillo_aspect_legend.csv",
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 15,
                maxNativeZoom: 19,
                maxZoom: 23,
                boundingBox: [
                  -106.9783220884045, 31.95579430955042, -106.96773434503986, 31.96242471583598,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
            ],
          },
          {
            name: "Slope",
            type: "header",
            demparser: "",
            controlled: false,
            tileformat: "tms",
            initialOpacity: 1,
            time: {
              enabled: false,
              type: "global",
              isRelative: true,
              current: new Date("2022-04-19T13:44:22Z"),
              start: "",
              end: "",
              format: "%Y-%m-%dT%H:%M:%SZ",
              refresh: "1 hours",
              increment: "5 minutes",
            },
            shape: "none",
            sublayers: [
              {
                name: "Slope 10m Regional",
                type: "tile",
                url: "Layers/portrillo_regional_slope/{z}/{x}/{y}.png",
                demtileurl: "Layers/portrillo_DEM/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                legend: "Layers/portrillo_regional_slope/slopelegend.csv",
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 9,
                maxNativeZoom: 13,
                maxZoom: 23,
                boundingBox: [
                  -107.44123839383117, 31.78402949781903, -106.79654100895651, 32.25249202592094,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "Slope 1m Hunts Hole",
                type: "tile",
                url: "Layers/HuntsHole_Slope/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                legend: "Layers/portrillo_regional_slope/slopelegend.csv",
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 14,
                maxNativeZoom: 17,
                maxZoom: 23,
                boundingBox: [
                  -106.97889305670077, 31.92641529168681, -106.96381932623324, 31.93993972184672,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "Slope 1m Kilbourne North Rim",
                type: "tile",
                url: "Layers/NorthRim_Slope/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                legend: "Layers/portrillo_regional_slope/slopelegend.csv",
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 14,
                maxNativeZoom: 17,
                maxZoom: 23,
                boundingBox: [
                  -106.9709488315368, 31.97811367853517, -106.95093436700662, 31.99308568520568,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "Slope 1m Kilbourne South Rim",
                type: "tile",
                url: "Layers/SouthRim_Slope/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                legend: "Layers/portrillo_regional_slope/slopelegend.csv",
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 14,
                maxNativeZoom: 17,
                maxZoom: 23,
                boundingBox: [
                  -106.96188443236635, 31.95245212214806, -106.94899360803925, 31.96466952541393,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "Slope 1m Kilbourne Southwest Rim",
                type: "tile",
                url: "Layers/SouthwestRim_Slope/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                legend: "Layers/portrillo_regional_slope/slopelegend.csv",
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 15,
                maxNativeZoom: 17,
                maxZoom: 23,
                boundingBox: [
                  -106.9783220884045, 31.95579631978293, -106.96773470346767, 31.96242471126321,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "Slope 20cm Kilbourne Southwest Rim",
                type: "tile",
                url: "Layers/SouthwestRim_20cm_Slope/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                legend: "Layers/portrillo_regional_slope/slopelegend.csv",
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 15,
                maxNativeZoom: 19,
                maxZoom: 23,
                boundingBox: [
                  -106.9783220884045, 31.95579430955042, -106.96773434503986, 31.96242471583598,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
            ],
          },
          {
            name: "Hillshade",
            type: "header",
            demparser: "",
            controlled: false,
            tileformat: "tms",
            initialOpacity: 1,
            time: {
              enabled: false,
              type: "global",
              isRelative: true,
              current: new Date("2022-04-19T13:44:22Z"),
              start: "",
              end: "",
              format: "%Y-%m-%dT%H:%M:%SZ",
              refresh: "1 hours",
              increment: "5 minutes",
            },
            shape: "none",
            sublayers: [
              {
                name: "Hillshade 10m Regional",
                type: "tile",
                url: "Layers/portrillo_hillshade/{z}/{x}/{y}.png",
                demtileurl: "Layers/portrillo_DEM/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 9,
                maxNativeZoom: 13,
                maxZoom: 23,
                boundingBox: [
                  -107.44123839383117, 31.78402949781903, -106.79654100895651, 32.25249202592094,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "Hillshade 1m Hunts Hole",
                type: "tile",
                url: "Layers/HuntsHole_Hillshade/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 14,
                maxNativeZoom: 17,
                maxZoom: 23,
                boundingBox: [
                  -106.97889305670077, 31.92641529168681, -106.96381932623324, 31.93993972184672,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "Hillshade 1m Kilbourne North Rim",
                type: "tile",
                url: "Layers/NorthRim_Hillshade/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 14,
                maxNativeZoom: 17,
                maxZoom: 23,
                boundingBox: [
                  -106.9709488315368, 31.97811367853517, -106.95093436700662, 31.99308568520568,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "Hillshade 1m Kilbourne South Rim",
                type: "tile",
                url: "Layers/SouthRim_Hillshade/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 14,
                maxNativeZoom: 17,
                maxZoom: 23,
                boundingBox: [
                  -106.96188443236635, 31.95245212214806, -106.94899360803925, 31.96466952541393,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "Hillshade 1m Kilbourne Southwest Rim",
                type: "tile",
                url: "Layers/SouthwestRim_Hillshade/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 15,
                maxNativeZoom: 17,
                maxZoom: 23,
                boundingBox: [
                  -106.9783220884045, 31.95579631978293, -106.96773470346767, 31.96242471126321,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
              {
                name: "Hillshade 20cm Kilbourne Southwest Rim",
                type: "tile",
                url: "Layers/SouthwestRim_20cm_Hillshade/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                tileformat: "tms",
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 15,
                maxNativeZoom: 19,
                maxZoom: 23,
                boundingBox: [
                  -106.9783220884045, 31.95579430955042, -106.96773434503986, 31.96242471583598,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
            ],
          },
          {
            name: "Basemaps",
            type: "header",
            demparser: "",
            controlled: false,
            tileformat: "tms",
            initialOpacity: 1,
            time: {
              enabled: false,
              type: "global",
              isRelative: true,
              current: new Date("2022-04-19T13:44:22Z"),
              start: "",
              end: "",
              format: "%Y-%m-%dT%H:%M:%SZ",
              refresh: "1 hours",
              increment: "5 minutes",
            },
            shape: "none",
            sublayers: [
              {
                name: "One Meter",
                type: "tile",
                url: "Layers/kilbournehole_1m_3857/{z}/{x}/{y}.png",
                demtileurl: "Layers/portrillo_DEM/{z}/{x}/{y}.png",
                demparser: "",
                controlled: false,
                tileformat: "tms",
                visibility: true,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 8,
                maxNativeZoom: 17,
                maxZoom: 23,
                boundingBox: [
                  -107.47297700557911, 31.65986801717055, -106.55954285121517, 32.28391307648736,
                ],
                time: {
                  enabled: false,
                  type: "global",
                  isRelative: true,
                  current: "2022-04-19T13:44:22Z",
                  start: "",
                  end: "",
                  format: "%Y-%m-%dT%H:%M:%SZ",
                  refresh: "1 hours",
                  increment: "5 minutes",
                },
                shape: "none",
              },
            ],
          },
        ],
        time: { enabled: false, visible: false, format: "" },
      },
      version: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
    em.create(Mission, {
      mission: "Test",
      config: {
        msv: {
          mission: "Test",
          site: "",
          masterdb: false,
          view: ["0", "0", "0"],
          radius: { major: "3396190", minor: "3396190" },
          mapscale: "",
        },
        projection: {
          custom: false,
          epsg: "",
          proj: "",
          globeproj: "webmercator",
          xmlpath: "",
          bounds: ["", "", "", ""],
          origin: ["", ""],
          reszoomlevel: 0,
          resunitsperpixel: 0,
        },
        look: {
          pagename: "postgres",
          minimalist: false,
          zoomcontrol: false,
          graticule: false,
          bodycolor: "",
          topbarcolor: "",
          toolbarcolor: "",
          mapcolor: "",
          swap: true,
          copylink: true,
          screenshot: true,
          fullscreen: true,
          help: true,
          logourl: "",
          helpurl: "",
        },
        panels: ["viewer", "map", "globe"],
        time: {
          enabled: false,
          visible: false,
          format: "%Y-%m-%dT%H:%M:%SZ",
        },
        tools: [
          { name: "Layers", icon: "buffer", js: "LayersTool" },
          { name: "Legend", icon: "format-list-bulleted-type", js: "LegendTool" },
          { name: "Info", icon: "information-variant", js: "InfoTool" },
          {
            name: "Sites",
            icon: "pin",
            js: "SitesTool",
            variables: {
              sites: [
                { name: "Site1", code: "S1", view: [-4.667975771815966, 137.370253354311, 16] },
                { name: "Site2", code: "S2", view: [-4.667985128408622, 137.3702734708786, 20] },
              ],
            },
          },
          { name: "Chemistry", icon: "flask", js: "ChemistryTool" },
          { name: "Draw", icon: "lead-pencil", js: "DrawTool" },
          { name: "FileManager", icon: "folder-multiple", js: "FileManagerTool" },
          {
            name: "Identifier",
            icon: "map-marker",
            js: "IdentifierTool",
            variables: { tile_with_DEM: { url: "Data/missionDEM.tif", unit: "m" } },
          },
          {
            name: "Measure",
            icon: "chart-areaspline",
            js: "MeasureTool",
            variables: { dem: "Data/missionDEM.tif" },
          },
        ],
        layers: [
          {
            name: "A Header",
            type: "header",
            initialOpacity: 1,
            sublayers: [
              {
                name: "S1 Drawings",
                kind: "none",
                type: "vector",
                url: "Drawn/S1_speDrawings.geojson",
                tms: true,
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                style: {
                  className: "s1drawings",
                  color: "undefined",
                  fillColor: "undefined",
                  weight: null,
                  fillOpacity: 1,
                  opacity: 1,
                },
                variables: {},
                radius: 1,
              },
              {
                name: "S2 Drawings",
                kind: "none",
                type: "vector",
                url: "Drawn/S2_speDrawings.geojson",
                tms: true,
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                style: {
                  className: "s2drawings",
                  color: "undefined",
                  fillColor: "undefined",
                  weight: null,
                  fillOpacity: 1,
                  opacity: 1,
                },
                variables: {},
                radius: 1,
              },
              {
                name: "ChemCam",
                kind: "none",
                type: "vector",
                url: "Layers/ChemCam/chemcam.json",
                tms: true,
                visibility: true,
                visibilitycutoff: 17,
                initialOpacity: 1,
                togglesWithHeader: true,
                style: {
                  className: "chemcam",
                  color: "prop:color1",
                  fillColor: "prop:color3",
                  weight: 2,
                  fillOpacity: 1,
                  opacity: 1,
                },
                variables: {
                  useKeyAsName: "TARGET",
                  chemistry: ["Al2O3", "CaO", "FeOT", "K2O", "MgO", "Na2O", "SiO2", "TiO2"],
                  search: "(TARGET)",
                },
                radius: 5,
              },
              {
                name: "Waypoints",
                kind: "none",
                type: "vector",
                url: "Layers/Waypoints/waypoints.json",
                legend: "Layers/Waypoints/legend.csv",
                tms: true,
                visibility: true,
                initialOpacity: 1,
                togglesWithHeader: true,
                style: {
                  className: "waypoints",
                  color: "white",
                  fillColor: "#000",
                  weight: 2,
                  fillOpacity: 1,
                  opacity: 1,
                },
                variables: {},
                radius: 8,
              },
              {
                name: "Polygon",
                kind: "none",
                type: "vector",
                url: "Layers/Polygon/polygon.geojson",
                tms: true,
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                style: {
                  className: "polygon",
                  color: "prop:somecolor",
                  fillColor: "prop:fill",
                  weight: 2,
                  fillOpacity: 0.7,
                  opacity: 1,
                },
                variables: {},
                radius: 4,
              },
              {
                name: "Line",
                kind: "none",
                type: "vector",
                url: "Layers/Line/line.json",
                tms: true,
                visibility: false,
                initialOpacity: 1,
                togglesWithHeader: true,
                style: {
                  className: "line",
                  color: "white",
                  fillColor: "white",
                  weight: 5,
                  fillOpacity: 1,
                  opacity: 1,
                },
                variables: {},
                radius: 1,
              },
              {
                name: "Tile with DEM",
                type: "tile",
                url: "Layers/TilewithDEM/Gale_HiRISE/{z}/{x}/{y}.png",
                demtileurl: "Layers/TilewithDEM/Gale_HiRISE_DEM/{z}/{x}/{y}.png",
                tms: true,
                visibility: true,
                initialOpacity: 1,
                togglesWithHeader: true,
                minZoom: 16,
                maxNativeZoom: 17,
                maxZoom: 22,
              },
            ],
          },
        ],
      },
      version: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  }
}
