/**
 * TileMap Resource XML Parser for AEGIS
 *
 * Parses tilemapresource.xml files generated by gdal2tiles to extract
 * tile layer metadata: zoom range, extent, origin, profile, and format.
 *
 * CRITICAL NOTE ON RESOLUTION VALUES:
 * ===================================
 * The `units-per-pixel` values in tilemapresource.xml DO NOT match the actual
 * tile grid used in S3. This was verified empirically on 2026-02-12:
 *
 *   - XML reports zoom 0 = 8192 m/pixel
 *   - API reports projResUnitsPerPixel = 12800
 *   - Tiles at coordinates predicted by 12800-scheme: HTTP 200 (exist)
 *   - Tiles at coordinates predicted by 8192-scheme: HTTP 403 (don't exist)
 *
 * This happens because the AEGIS tile generation pipeline uses the mission's
 * `projResUnitsPerPixel` as the tile grid resolution, but gdal2tiles computes
 * the XML resolution from the raster's native pixel dimensions. These are
 * fundamentally different values:
 *   - API `projResUnitsPerPixel`: Tile grid resolution (controls tile coordinate math)
 *   - XML `units-per-pixel`: Raster's native resolution (informational only)
 *
 * Therefore:
 *   USE the XML for: zoom range, extent, origin, profile, tile format
 *   DO NOT USE the XML `units-per-pixel` for TileGrid construction
 *   USE the API `projResUnitsPerPixel` for TileGrid resolutions
 */

/**
 * Fetch and parse a tilemapresource.xml file.
 *
 * @param url - Full URL to the tilemapresource.xml file
 * @returns Parsed metadata, or null if fetch/parse fails
 *
 * @example
 * ```typescript
 * const meta = await fetchTilemapResource(
 *   "https://ares-aegis.s3.us-gov-west-1.amazonaws.com/NAC_POLE_SOUTH/tilemapresource.xml"
 * );
 * if (meta) {
 *   console.log(`Zoom range: ${meta.minZoom}-${meta.maxZoom}`);
 *   console.log(`Profile: ${meta.profile}`);
 * }
 * ```
 */
export async function fetchTilemapResource(url: string): Promise<TilemapMetadata | null> {
  try {
    const response = await fetch(url);
    if (!response.ok) {
      console.warn(`[TilemapResource] Failed to fetch ${url}: HTTP ${response.status}`);
      return null;
    }
    const xmlText = await response.text();
    return parseTilemapResourceXml(xmlText);
  } catch (error) {
    console.warn(`[TilemapResource] Error fetching ${url}:`, error);
    return null;
  }
}

/**
 * Parse tilemapresource.xml content string into structured metadata.
 *
 * @param xmlText - Raw XML string content
 * @returns Parsed metadata, or null if parsing fails
 */
export function parseTilemapResourceXml(xmlText: string): TilemapMetadata | null {
  try {
    const parser = new DOMParser();
    const doc = parser.parseFromString(xmlText, "text/xml");

    // Check for parse errors
    const parseError = doc.querySelector("parsererror");
    if (parseError) {
      console.warn("[TilemapResource] XML parse error:", parseError.textContent);
      return null;
    }

    // Title
    const title = doc.querySelector("Title")?.textContent ?? "";

    // SRS
    const srs = doc.querySelector("SRS")?.textContent ?? "";

    // BoundingBox
    const bbox = doc.querySelector("BoundingBox");
    const boundingBox = {
      minX: parseFloat(bbox?.getAttribute("minx") ?? "0"),
      minY: parseFloat(bbox?.getAttribute("miny") ?? "0"),
      maxX: parseFloat(bbox?.getAttribute("maxx") ?? "0"),
      maxY: parseFloat(bbox?.getAttribute("maxy") ?? "0"),
    };

    // Origin
    const originEl = doc.querySelector("Origin");
    const origin = {
      x: parseFloat(originEl?.getAttribute("x") ?? "0"),
      y: parseFloat(originEl?.getAttribute("y") ?? "0"),
    };

    // TileFormat
    const tileFormatEl = doc.querySelector("TileFormat");
    const tileFormat = {
      width: parseInt(tileFormatEl?.getAttribute("width") ?? "256", 10),
      height: parseInt(tileFormatEl?.getAttribute("height") ?? "256", 10),
      mimeType: tileFormatEl?.getAttribute("mime-type") ?? "image/png",
      extension: tileFormatEl?.getAttribute("extension") ?? "png",
    };

    // TileSets profile
    const tileSetsEl = doc.querySelector("TileSets");
    const profileAttr = tileSetsEl?.getAttribute("profile") ?? "raster";
    const profile = profileAttr === "mercator" ? "mercator" : "raster";

    // Individual TileSet entries
    const tileSetEls = doc.querySelectorAll("TileSet");
    const reportedTileSets: TilemapMetadata["reportedTileSets"] = [];

    tileSetEls.forEach((el) => {
      const zoom = parseInt(el.getAttribute("href") ?? el.getAttribute("order") ?? "0", 10);
      const unitsPerPixel = parseFloat(el.getAttribute("units-per-pixel") ?? "0");
      reportedTileSets.push({ zoom, unitsPerPixel });
    });

    // Sort by zoom level
    reportedTileSets.sort((a, b) => a.zoom - b.zoom);

    const minZoom = reportedTileSets.length > 0 ? reportedTileSets[0].zoom : 0;
    const maxZoom =
      reportedTileSets.length > 0 ? reportedTileSets[reportedTileSets.length - 1].zoom : 0;

    return {
      title,
      srs,
      boundingBox,
      origin,
      tileFormat,
      profile,
      reportedTileSets,
      minZoom,
      maxZoom,
    };
  } catch (error) {
    console.warn("[TilemapResource] Error parsing XML:", error);
    return null;
  }
}

/**
 * Build a complete tile URL for fetching tilemapresource.xml from a layer path.
 *
 * @param layerPath - The sublayer path (e.g., "NAC_POLE_SOUTH_CM_AVG_MERGE")
 * @param missionId - Mission ID for constructing local paths
 * @returns URL to the tilemapresource.xml file
 */
export function buildTilemapResourceUrl(layerPath: string, missionId: number): string {
  if (layerPath.startsWith("http://") || layerPath.startsWith("https://")) {
    // External layer - append tilemapresource.xml to the base path
    return `${layerPath}/tilemapresource.xml`;
  }
  // Local layer
  return `/static/missionFiles/${missionId}/Layers/${layerPath}/tilemapresource.xml`;
}
