// This file is for use with the vscode plugin, Simple REST Client
// (https://marketplace.visualstudio.com/items?itemName=Tino.simple-rest-client)
// With the plugin installed, click the "Send Request" text that appears above the `POST` entry below to hit local dev and test the endpoint.

POST http://localhost:4000/api/v1/emss/rexPet
Content-Type: application/json
emss-token: {{$dotenv EMSS_TOKEN}}

{
  "rexUuid": "e99598a1-942c-4a78-b9ea-fd572149e33b",
  // set this timestamp to some time today but before now for testing
  "petStartStopTimestamp": "2025-06-20T01:00:00Z",
  "petValueAtStartStop": "00:05:30",
  "petRunning": true
}