const lotr = [
  "The Shire",
  "Hobbiton",
  "Buckland",
  "Tookland",
  "Bywater",
  "Bag End",
  "Rivendell (Imladris)",
  "The Last Homely House",
  "The Ford of Bruinen",
  "The Hall of Fire",
  "Moria (Khazad-dûm)",
  "The Chamber of Mazarbul",
  "The Bridge of Khazad-dûm",
  "Lothlórien",
  "Caras Galadhon",
  "Cerin Amroth",
  "The Golden Wood",
  "Rohan",
  "Edoras",
  "Helm's Deep",
  "The Plains of Rohan",
  "The Riddermark",
  "Gondor",
  "Minas Tirith",
  "Osgiliath",
  "The White Tree of Gondor",
  "The Tower of Ecthelion",
  "Mordor",
  "Mount Doom (Orodruin)",
  "Barad-dûr",
  "The Black Gate (Morannon)",
  "Cirith Ungol",
  "Isengard",
  "Orthanc",
  "The Tower of Isengard",
  "Fangorn Forest",
  "The Ents' Home",
  "Treebeard's Hill",
  "The Dead Marshes",
  "Bree",
  "The Prancing Pony",
  "The Old Forest Road",
  "The Lonely Mountain (Erebor)",
  "The Front Gate",
  "The Treasure Hall",
  "Dale",
  "Mirkwood",
  "The Elvenking's Halls (Thranduil's Realm)",
  "Lake-town (Esgaroth)",
  "The Misty Mountains",
  "Goblin-town",
  "The High Pass",
  "The Paths of the Dead",
  "The Sea of Rhûn",
  "Harad",
  "The Black Land",
  "The Grey Havens (Mithlond)",
  "Angmar",
  "Forodwaith",
  "Eregion",
  "Rhovanion",
  "Dagorlad",
  "Dol Guldur",
  "Rhosgobel",
  "Amon Hen and Amon Lhaw",
  "The Glittering Caves of Aglarond",
  "Eriador",
  "The Barrow-downs",
  "The Weather Hills",
  "The Great East Road",
  "Forlindon and Harlindon",
  "The Grey Havens",
  "The Tower Hills",
  "Numenor (Númenor)",
  "Armenelos",
  "Andúnië",
  "Meneltarma",
  "Enedwaith",
  "Tharbad",
  "Gwathló (The Greyflood)",
  "The East Bight",
  "The Wold",
  "The East Wall",
  "The Sea of Núrnen",
  "Nurn",
  "The Slag-hills",
  "Minhiriath",
  "Lond Daer (Great Haven)",
  "The Bay of Belfalas",
  "Dol Amroth",
  "Edhellond",
  "Umbar",
  "Havens of Umbar",
  "Near Harad",
  "The Far Harad",
  "The Mountains of Shadow",
  "Khand",
  "Rhun",
  "The Sea of Rhûn",
  "The Iron Hills",
  "Dorwinion",
  "Druwaith Iaur",
  "Angmar",
  "Carn Dûm",
  "The Witch-king's Fortress",
  "The Ettenmoors",
  "Rhosgobel",
  "Dagorlad",
  "Nan Curunír",
  "Neldoreth and Region",
  "Esgalduin",
  "Esgaroth",
  "Tolfalas",
  "Anor Londo",
  "Taur-en-Faroth",
  "Angband",
  "Lindon",
  "The Grey Havens",
  "The Tower Hills",
  "Ithilien",
  "Henneth Annûn",
  "Faramir's Hideout",
  "Minas Morgul",
  "The Brown Lands",
  "The Cross-roads",
  "Ossiriand",
  "The Seven Rivers",
  "Talath Dirnen",
  "Hithlum",
  "Eithel Sirion",
  "The Helcaraxë",
  "Tumladen",
  "Dorthonion",
  "Thargelion",
  "Ramdal",
  "Ered Wethrin",
  "Nan Elmoth",
  "Nan-tathren",
  "Brethil",
  "Amon Obel",
  "The Hidden Way",
  "Nargothrond",
  "Nan Dungortheb",
  "Nirnaeth Arnoediad",
  "Amon Ereb",
  "The Hill of Himring",
  "Ondolindë (Gondolin)",
  "The Halls of Mandos",
  "The Helcaraxë",
  "The Isle of Werewolves",
  "The Fields of Celebrant",
  "Celeborn's Orchard",
  "Morthond Vale",
  "Cair Andros",
  "Amon Dîn",
  "Erech",
  "Pelargir",
  "Isle of Tol Brandir",
  "Anfalas",
  "Isle of Himling",
  "The Deadman Dike",
  "The Crossings of Poros",
  "The Mouths of Anduin",
  "Ered Lithui",
  "The Black Ithilien",
  "The Beacon Hills",
  "Eryn Vorn",
  "Woodland Realm",
  "Nanduhirion",
  "North Ithilien",
  "Ephel Dúath",
  "Gorgoroth",
  "The Marshes of Nindalf",
];

export default lotr;
