stages:
  - stageless

  # This isn't used, but there are some tests within the FIT developer-ecosystem set that
  # expect to be run in the `test` stage. These tests are not run in this pipeline due to it not
  # having any of the requirements (e.g. Golang or PHP code). We could call them all out and specify
  # where they would run, or remove them, but it's easier to just make this unused "test".
  - test

default:
  timeout: 10 minutes

variables:
  HOME: "/tmp" # required for openshift for now
  CURRENT_NODE_VERSION_IMAGE: "$CI_REGISTRY/emss/docker-images/node:20.11.0-alpine"
  # "Future" might be older if waiting on a newer version to come out
  FUTURE_NODE_VERSION_IMAGE: "$CI_REGISTRY/emss/docker-images/node:21-alpine"

  # Default image unless otherwise specified
image: "$CURRENT_NODE_VERSION_IMAGE"

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .next/cache/

# also run standard FIT dependency and package checks
# https://gitlab.fit.nasa.gov/developer-ecosystem/ci-job-templates
include:
  # Common jobs that basically all repos should run
  - project: "developer-ecosystem/ci-job-templates"
    ref: 5.4.2
    file: "/rollups/all-projects.gitlab-ci.yml"

  # Docker-in-Docker template for building docker images using docker runners
  - project: "developer-ecosystem/ci-job-templates"
    ref: 5.4.2
    file: "/extends/dind.gitlab-ci.yml"

  # A11y tests. Disabled for now.
  # - template: "Verify/Accessibility.gitlab-ci.yml"

  # Code quality checks
  - project: "emss/gitlab-templates"
    ref: 1.2.2
    file: "/jobs/code-quality.gitlab-ci.yml"

  # Fitdock deploy template
  - project: "emss/gitlab-templates"
    ref: 1.2.2
    file: "/jobs/fitdock-deploy.gitlab-ci.yml"

  # EMSS shared dev server helpers (carbon, iron, oxygen, etc)
  - project: "emss/gitlab-templates"
    ref: 1.2.2
    file: "/jobs/emss-shared-dev.gitlab-ci.yml"

  # Kaniko build template
  - project: "emss/gitlab-templates"
    ref: 1.2.2
    file: "/jobs/kaniko-build.gitlab-ci.yml"

  # Retag job template
  - project: "emss/gitlab-templates"
    ref: 1.2.2
    file: "/jobs/container-retag.gitlab-ci.yml"

# Overrride some properties on FIT jobs. Unfortunately using a template for these
# make GitLab angry, so a lot of repetition
project-check:
  stage: stageless
  needs: []
nodejs-scan-sast:
  stage: stageless
  needs: []
semgrep-sast:
  stage: stageless
  needs: []
sast:
  stage: stageless
  needs: []
secret_detection:
  stage: stageless
  needs: []
code-count:
  stage: stageless
  needs: []
yaml-lint:
  stage: stageless
  needs: []
job-report-visualization:
  stage: stageless
  needs: []
deprecated-keywords:
  stage: stageless
  needs: []
file-count:
  stage: stageless
  needs: []
# accessibility:
#   stage: stageless
#   needs: ["some deploy job or a running system in GitLab"]
#   tags: ["openshift"]
dependency-check:
  stage: stageless
  tags: ["docker", "linux"] # can't use openshift (yet?)
  needs: ["install_dependencies"] # dependency-check takes a while, don't wait for "test" job
  rules:
    - if: '$CI_COMMIT_BRANCH == "int" || $CI_COMMIT_BRANCH == "prod"'

npm-audit:
  stage: stageless
  image: $CI_REGISTRY/emss/docker-images/node-ci:npm-audit
  needs: []
  tags: ["openshift"]
  allow_failure: true
  script:
    # Runs `npm audit --json` then sends the results to EMSS dashboard (only on EMSS major branches)
    - >
      if
      [ "${CI_COMMIT_REF_SLUG}" == "prod" ] ||
      [ "${CI_COMMIT_REF_SLUG}" == "int" ] ||
      [ "${CI_COMMIT_REF_SLUG}" == "stable" ] ||
      [ "${CI_COMMIT_REF_SLUG}" == "beta" ] ||
      [ "${CI_COMMIT_REF_SLUG}" == "alpha" ];
      then
        node /postAuditReport.js;
      fi

    # Run this without --json to make a pretty-print for the job log, plus will pass/fail the job
    - npm audit

install_dependencies:
  stage: stageless
  # This could be openshift, but it runs faster in a VM; other jobs rely on it, so get it done ASAP
  tags: ["docker", "linux"]
  script:
    - npm ci
  artifacts:
    expire_in: 1 day
    paths:
      - ./node_modules/*

#
# Creates Software Bill of Materials
#
node-sbom:
  stage: stageless
  allow_failure: true
  tags: ["docker", "linux"] # Can't be openshift due to it not pulling latest tag
  needs: ["install_dependencies"]
  image: $CI_REGISTRY/emss/docker-images:node-ci-sbom
  script:
    - /create-and-compare-bom.sh ./BOM.md
  artifacts:
    when: always
    paths:
      - "./bom.json"
      - "./new-bom.md"
    expire_in: 1 day

# Template for `test` and `test-node-next` jobs, adding database service, etc.
.test_template:
  stage: stageless
  needs:
    - install_dependencies
    - make-dotenv
  variables:
    # define variables used by Node app
    DB_HOST: postgres-test-container
    DB_PASS: test-only-password
    DB_NAME: aegis

    # plug those same variables into the Postgres container we're spinning up
    POSTGRES_PASSWORD: test-only-password
    POSTGRES_DB: aegis
  services:
    # image should match database used in docker-compose.yml
    - name: $CI_REGISTRY/emss/docker-images/postgres:postgis-14-alpine
      alias: postgres-test-container
  tags: ["docker", "linux"]
  before_script:
    # Remove lines from .env file. See "Variable Precedence" section above
    - sed -i '/DB_PASS/d' .env
    - sed -i '/DB_HOST/d' .env
    - sed -i '/DB_NAME/d' .env

test:
  extends: .test_template
  script:
    - npm run migrate:up
    - npm run lint
    - npm run tsc
    - npm run test:coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: ./coverage/cobertura-coverage.xml
      junit:
        - junit.xml
    paths:
      - ./coverage/*
    expire_in: 1 day

# test against next version of node that AEGIS may use, but allow to fail
test-node-next:
  extends: .test_template
  image: "$FUTURE_NODE_VERSION_IMAGE"
  allow_failure: true
  script:
    - npm run migrate:up
    - npm run lint
    - npm run tsc
    - npm t

make-dotenv:
  image: "$CI_REGISTRY/emss/docker-images:envsubst-bash-in-envsubst"
  stage: stageless
  needs: []
  tags: ["openshift"]
  script:
    # Copy contents of DOTENV_SECRET from CI/CD variables to a new .env.secret file
    - echo "${DOTENV_SECRET}" > ./.env.secret

    # Determine which docker image type (dev, int, or prod) to deploy based on branch
    # Append the commit sha in order to ensure the correct build is being deployed in the case
    # multiple devs are building images simutaneously
    - >
      if [ "${CI_COMMIT_REF_SLUG}" == "prod" ]; then
          IMAGE_VERSION="prod-${CI_COMMIT_SHORT_SHA}"
      elif [ "${CI_COMMIT_REF_SLUG}" == "int" ]; then
          IMAGE_VERSION="int-${CI_COMMIT_SHORT_SHA}"
      else
          IMAGE_VERSION="dev-${CI_COMMIT_SHORT_SHA}"
      fi

    # Export the variable so it can be read inside the make-dotenv.sh script
    - export IMAGE_VERSION
    # Save image version into an artifact to be read later in other job scripts
    - echo "IMAGE_VERSION=${IMAGE_VERSION}" >> pipelineVariables.env

    # make-dotenv.sh should detect the script directory to read .env.template and write .env
    # relatively, but Alpine Linux uses standard POSIX sh, not Bash, which cannot do this [1]. So
    # we need to `cd` into the ./scripts directory first when using Alpine.
    #
    # Ref: [1] https://stackoverflow.com/a/49794678/2782380
    - cd ./scripts
    - bash ./make-dotenv.sh

  artifacts:
    reports:
      dotenv: pipelineVariables.env
    paths:
      - .env
    expire_in: 1 day

#
# Build container images
# Vite is not used in production, so we don't need to build it
#

.kaniko-build-template:
  extends: .emss-kaniko-build
  stage: stageless
  tags: ["docker", "linux"]
  needs:
    - make-dotenv

docker:build:nginx:
  extends: .kaniko-build-template
  variables:
    SERVICE_NAME: nginx
    MULTISTAGE_TARGET: prod
    NGINX_BASE_IMAGE: eegitlabregistry.fit.nasa.gov/emss/docker-images/nginx:1.23.0-alpine
    NODE_BASE_IMAGE: $CURRENT_NODE_VERSION_IMAGE
    MAP_ENV_VARS_TO_BUILD_ARGS: |
      NGINX_BASE_IMAGE
      NODE_BASE_IMAGE

docker:build:gdal:
  extends: .kaniko-build-template
  variables:
    SERVICE_NAME: gdal
    MULTISTAGE_TARGET: base
    GDAL_BASE_IMAGE: eegitlabregistry.fit.nasa.gov/emss/docker-images/deploy:gdal
    MAP_ENV_VARS_TO_BUILD_ARGS: |
      GDAL_BASE_IMAGE

docker:build:apiv1:
  extends: .kaniko-build-template
  variables:
    SERVICE_NAME: apiv1
    MULTISTAGE_TARGET: prod
    APIV1_BASE_IMAGE: $CURRENT_NODE_VERSION_IMAGE
    MAP_ENV_VARS_TO_BUILD_ARGS: |
      APIV1_BASE_IMAGE

#
# Retag docker images after necessary jobs pass (e.g. unit testing passes)
#
docker:retag:
  extends: .emss-container-retag
  needs:
    - make-dotenv
    - job: test
      artifacts: false
    - job: docker:build:nginx
      artifacts: false
    - job: docker:build:gdal
      artifacts: false
    - job: docker:build:apiv1
      artifacts: false
  variables:
    RETAG_SERVICE_IMAGES: |
      nginx
      gdal
      apiv1

deploy:artifactize-committed-files:
  image: "$CI_REGISTRY/emss/docker-images:envsubst-bash-in-envsubst"
  stage: stageless
  needs: []
  tags: ["openshift"]
  script:
    - echo "This job runs no commands, just turns .fitdock.yml and docker-compose.yml into artifacts"
  artifacts:
    paths:
      - .fitdock.yml
      - docker-compose.yml
    expire_in: 1 day

.deploy-template:
  extends: .emss-fitdock-deploy # use job template from gitlab-templates repo
  stage: stageless
  timeout: 10 minutes

deploy:dev1:
  extends: .deploy-template
  tags: ["emss-aegis-dev1"]
  needs:
    - make-dotenv
    - docker:retag
    - deploy:artifactize-committed-files
  environment:
    name: development1
    url: $URL
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_DEV1 #CI/CD Variable
    URL: https://aegis-dev.fit.nasa.gov
  when: manual

deploy:carbon:
  extends:
    - .deploy-template
    - .carbon-deploy
  needs:
    - make-dotenv
    - docker:retag
    - deploy:artifactize-committed-files
  when: manual

deploy:int:
  extends: .deploy-template
  tags: ["emss-aegis-int"]
  needs:
    - make-dotenv
    - docker:retag
    - deploy:artifactize-committed-files
  environment:
    name: integration
    url: $URL
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_INT #CI/CD Variable
    URL: https://aegis-int.fit.nasa.gov
  only:
    - int

deploy:prod:
  extends: .deploy-template
  tags: ["emss-aegis-prod"]
  needs:
    - make-dotenv
    - docker:retag
    - deploy:artifactize-committed-files
  environment:
    name: production
    url: $URL
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_PROD #CI/CD Variable
    URL: https://aegis.fit.nasa.gov
  when: manual
  only:
    - prod

.db-export-template:
  needs: []
  # I don't think we want to do this, because I don't think we want GitLab to consider this a
  # deployment. It's just grabbing some data off of Production.
  # environment:
  #   name: production
  #   url: https://aegis.fit.nasa.gov
  when: manual
  stage: stageless
  timeout: 10 minutes
  variables:
    GIT_STRATEGY: none
  script:
    # init sudo ability
    - echo "${DEPLOY_SUDO_PASS}" | sudo -S touch /tmp/somefile
    - PROJECT_DIR=$(pwd)
    - cd /opt/aegis
    - sudo docker compose exec database pg_dump -U postgres aegis > "${PROJECT_DIR}/aegis.sql"
  artifacts:
    paths:
      - aegis.sql
    expire_in: 1 day

z:db-export:prod:
  extends: .db-export-template
  tags: ["emss-aegis-prod"]
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_PROD #CI/CD Variable

z:db-export:int:
  extends: .db-export-template
  tags: ["emss-aegis-int"]
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_INT #CI/CD Variable

z:db-export:dev1:
  extends: .db-export-template
  tags: ["emss-aegis-dev1"]
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_DEV1 #CI/CD Variable

z:db-export:carbon:
  extends:
    - .db-export-template
    - .carbon-access

.db-import-template:
  when: manual
  stage: stageless
  timeout: 10 minutes
  variables:
    GIT_STRATEGY: none
  script:
    # init sudo ability
    - echo "${DEPLOY_SUDO_PASS}" | sudo -S touch /tmp/somefile
    - PROJECT_DIR=$(pwd)
    - cd /opt/aegis
    - cp "${PROJECT_DIR}/aegis.sql" /d1/aegis/db-init/aegis.sql

    # Stop docker compose, then remove database files
    - sudo /usr/bin/docker compose down --remove-orphans
    - sudo rm -rf /d1/aegis/postgres

    # Bring docker compose back up, which will use the file at /d1/aegis/db-init/aegis.sql, then remove it
    - sudo /usr/bin/docker compose up -d
    - sudo rm -f /d1/aegis/db-init/aegis.sql

    # Migrations will be run when the apiv1 container restarts

z:db-import:dev1:
  extends: .db-import-template
  tags: ["emss-aegis-dev1"]
  needs: ["z:db-export:prod"]
  environment:
    name: development
    url: $URL
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_DEV1 #CI/CD Variable
    URL: https://aegis-dev.fit.nasa.gov

z:db-import:carbon:
  extends:
    - .db-import-template
    - .carbon-deploy
  needs: ["z:db-export:prod"]

z:db-import:int:
  extends: .db-import-template
  tags: ["emss-aegis-int"]
  needs: ["z:db-export:prod"]
  environment:
    name: integration
    url: $URL
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_INT #CI/CD Variable
    URL: https://aegis-int.fit.nasa.gov

.container-logs-template:
  when: manual
  needs: []
  stage: stageless
  timeout: 10 minutes
  variables:
    GIT_STRATEGY: none
  script:
    - echo "${DEPLOY_SUDO_PASS}" | sudo -S touch /tmp/somefile
    - cd /opt/aegis
    - sudo docker compose logs nginx
    - sudo docker compose logs database
    - sudo docker compose logs gdal
    - sudo docker compose logs apiv1

z:logs:dev1:
  extends: .container-logs-template
  tags: ["emss-aegis-dev1"]
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_DEV1 #CI/CD Variable

z:logs:carbon:
  extends:
    - .container-logs-template
    - .carbon-access

z:logs:int:
  extends: .container-logs-template
  tags: ["emss-aegis-int"]
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_INT #CI/CD Variable

z:logs:prod:
  extends: .container-logs-template
  tags: ["emss-aegis-prod"]
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_PROD #CI/CD Variable
