export const NODATA_SENTINEL = -1100101;
export const MAX_ELEVATION_PATH_VERTICES = 2_000;
export const ELEVATION_BODY_LIMIT = "1mb";
export const ELEVATION_RATE_LIMIT_BURST_SAMPLES = 150_000;
export const ELEVATION_RATE_LIMIT_SAMPLES_PER_SECOND = 30_000;
export const ELEVATION_RATE_LIMIT_IDLE_TTL_MS = 15 * 60_000;
export const ELEVATION_RATE_LIMIT_MAX_USERS = 2_000;
