import { MikroORM } from "@mikro-orm/postgresql";
import config from "server/database/mikro-orm.config";
import { globalValues } from "server/express/global";
import { App_User_db, Doc_Listing_db } from "server/database/models/_allModels";
import AppUserFactory from "../fixtures/entityFactories/AppUserFactory";
import DocListingFactory from "../fixtures/entityFactories/DocListingFactory";
import supertest from "supertest";
import app from "server/express/restApi";
import { createMockAutomergeRepo } from "../helpers/mockAutomergeRepo";

// suppress socketio calls because they won't work during vitest testing
vi.mock("server/express/sockets", async () => {
  const actual = await vi.importActual("server/express/sockets");
  return {
    ...actual,
    emitStoreUpsert: vi.fn(),
    emitStoreDelete: vi.fn(),
  };
});

let testAppUserNoPerms: App_User_db;
let testAppUser: App_User_db;
let testSuperAdmin: App_User_db;
let testAutomergeDocListings: Doc_Listing_db[];
let testMissionsPartial: Partial<Mission>[];

beforeAll(async () => {
  // Initialize MikroORM and set it in globalValues
  globalValues.orm = await MikroORM.init(config);
  const em = globalValues.orm.em.fork();

  // Create test missions
  // First create doc_listing_db records to get autogenerated IDs
  testAutomergeDocListings = await new DocListingFactory(em)
    .each((record, index) => {
      record.automergeUrl = `automerge:VitestTestMission${index + 1}`;
    })
    .create(3);
  // Then create testMissionsPartial using the autogenerated IDs from the automerge records
  testMissionsPartial = [
    {
      id: testAutomergeDocListings[0].missionId,
      name: "Vitest Test Mission 1",
      archivedAt: null,
    },
    {
      id: testAutomergeDocListings[1].missionId,
      name: "Vitest Test Mission 2",
      archivedAt: null,
    },
    {
      id: testAutomergeDocListings[2].missionId,
      name: "Vitest Test Mission 3",
      archivedAt: null,
    },
  ];
  // Last, create mock automerge repo with test missions partials from above
  globalValues.automergeRepo = createMockAutomergeRepo(testMissionsPartial);

  testAppUserNoPerms = await new AppUserFactory(em).createOne({
    username: "Vitest testNoPerms",
  });
  testAppUser = await new AppUserFactory(em).createOne({
    username: "Vitest homePageItems",
    permissionList: [
      {
        missionId: testMissionsPartial[0].id,
        permissions: {
          edit: true,
          view: true,
        },
      },
      {
        missionId: testMissionsPartial[1].id,
        permissions: {
          edit: false,
          view: false,
        },
      },
    ],
  });
  testSuperAdmin = await new AppUserFactory(em).createOne({
    username: "Vitest testSuperAdminForHomePageItems",
    isSuperAdmin: true,
  });
});

describe("REX API Endpoint", () => {
  let aegisSessionCookie: string;
  let aegisSessionSigCookie: string;

  test("Returns auth failure", async () => {
    const res = await supertest(app).get("/api/v1/missionHomepageItems");
    expect(res.statusCode).toBe(401);
  });

  test("Returns login session", async () => {
    const res = await supertest(app)
      .post("/api/v1/auth/login")
      .send({ username: testAppUser.username, password: "superSecretPassword" });
    expect(res.statusCode).toBe(200); //check response from login
    expect(res.body.status).toEqual("success");
    aegisSessionCookie = res.header["set-cookie"][0];
    aegisSessionSigCookie = res.header["set-cookie"][1];
  });

  describe("GET request", () => {
    test("User with viewable missions", async () => {
      const res = await supertest(app)
        .get("/api/v1/missionHomePageItems")
        .set("Cookie", [aegisSessionCookie, aegisSessionSigCookie]);

      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      expect(res.body.data.length).toEqual(1);
    });

    test("Login as super admin", async () => {
      await supertest(app).get("/api/v1/auth/logout");

      const res = await supertest(app)
        .post("/api/v1/auth/login")
        .send({ username: testSuperAdmin.username, password: "superSecretPassword" });

      expect(res.statusCode).toBe(200);
      expect(res.body.status).toEqual("success");
      expect(res.body.data.isSuperAdmin).toBeTruthy();
      aegisSessionCookie = res.header["set-cookie"][0];
      aegisSessionSigCookie = res.header["set-cookie"][1];
    });

    test("User with all missions", async () => {
      const res = await supertest(app)
        .get("/api/v1/missionHomePageItems")
        .set("Cookie", [aegisSessionCookie, aegisSessionSigCookie]);

      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      expect(res.body.data.length).toBeGreaterThan(1);
    });

    test("Login as user with no viewable missions", async () => {
      await supertest(app).get("/api/v1/auth/logout");

      const res = await supertest(app)
        .post("/api/v1/auth/login")
        .send({ username: testAppUserNoPerms.username, password: "superSecretPassword" });

      expect(res.statusCode).toBe(200);
      expect(res.body.status).toEqual("success");
      expect(res.body.data.isSuperAdmin).toBeFalsy();
      aegisSessionCookie = res.header["set-cookie"][0];
      aegisSessionSigCookie = res.header["set-cookie"][1];
    });

    test("User with no viewable missions", async () => {
      const res = await supertest(app)
        .get("/api/v1/missionHomePageItems")
        .set("Cookie", [aegisSessionCookie, aegisSessionSigCookie]);

      expect(res.statusCode).toBe(401);
      expect(res.body.status).toBe("failure");
      expect(res.body.message).toBe("Unauthorized");
    });
  });
});

afterAll(async () => {
  //Cleanup our Database
  const em = globalValues.orm.em.fork();
  for (let i = 0; i < testAutomergeDocListings.length; i++) {
    await em.nativeDelete(Doc_Listing_db, { missionId: testAutomergeDocListings[i].missionId });
  }
  await em.nativeDelete(App_User_db, { id: testAppUser.id });
  await em.nativeDelete(App_User_db, { id: testSuperAdmin.id });
  await em.nativeDelete(App_User_db, { id: testAppUserNoPerms.id });

  // Closing the DB connection allows Vitest to exit successfully.
  await globalValues.orm.close();
  globalValues.orm = null;

  vi.restoreAllMocks();
});
