import { MikroORM } from "@mikro-orm/postgresql";
import config from "server/database/mikro-orm.config";
import { globalValues } from "server/express/global";
import {
  App_User_db,
  Doc_Listing_db,
  Mission_Permission_db,
} from "server/database/models/_allModels";
import DocListingFactory from "../fixtures/entityFactories/DocListingFactory";
import {
  asSuperUser,
  asUser,
  upsertAppUser,
  upsertPublicUser,
  grantMissionPerms,
} from "../fixtures/access";
import supertest from "supertest";
import app from "server/express/restApi";
import { createMockAutomergeRepo } from "../helpers/mockAutomergeRepo";

// suppress socketio calls because they won't work during vitest testing
vi.mock("server/express/sockets", async () => {
  const actual = await vi.importActual("server/express/sockets");
  return {
    ...actual,
    emitStoreUpsert: vi.fn(),
    emitStoreDelete: vi.fn(),
  };
});

const GRANTED_UUPIC = "vitest-homepage-granted";
const SUPER_UUPIC = "vitest-homepage-super";
const NO_PERMS_UUPIC = "vitest-homepage-noperms";

let grantedUser: App_User_db;
let publicUser: App_User_db;
let testAutomergeDocListings: Doc_Listing_db[];
let testMissionsPartial: Partial<Mission>[];

beforeAll(async () => {
  globalValues.orm = await MikroORM.init(config);
  const em = globalValues.orm.em.fork();

  // Create doc_listing_db records first, so the autogenerated ids can key the mock missions.
  testAutomergeDocListings = await new DocListingFactory(em)
    .each((record, index) => {
      record.automergeUrl = `automerge:VitestTestMission${index + 1}`;
    })
    .create(3);

  testMissionsPartial = testAutomergeDocListings.map(
    (listing, index): Partial<Mission> => ({
      id: listing.missionId,
      name: `Vitest Test Mission ${index + 1}`,
      archivedAt: null,
    })
  );

  globalValues.automergeRepo = createMockAutomergeRepo(testMissionsPartial);

  grantedUser = await upsertAppUser(em, GRANTED_UUPIC);
  await grantMissionPerms(em, {
    missionId: testMissionsPartial[0].id,
    userId: grantedUser.id,
    permLevel: "edit",
  });

  await upsertAppUser(em, SUPER_UUPIC);

  // Recorded up front so recordLogin has nothing to create mid-test.
  await upsertAppUser(em, NO_PERMS_UUPIC);

  publicUser = await upsertPublicUser(em);
});

/** Only the missions this test created; the shared database holds unrelated ones. */
const ownIds = (body: { data: MissionHomepageItem[] }): number[] => {
  const mine = new Set(testMissionsPartial.map((m) => m.id));
  return body.data.filter((item) => mine.has(item.id)).map((item) => item.id);
};

describe("missionHomepageItems API Endpoint", () => {
  describe("GET request", () => {
    test("User sees only the mission granted to them", async () => {
      const res = await supertest(app)
        .get("/api/v1/missionHomepageItems")
        .set(asUser(GRANTED_UUPIC));

      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      expect(ownIds(res.body)).toEqual([testMissionsPartial[0].id]);
    });

    test("Super user sees every mission", async () => {
      const res = await supertest(app)
        .get("/api/v1/missionHomepageItems")
        .set(asSuperUser(SUPER_UUPIC));

      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      expect(ownIds(res.body).sort()).toEqual(testMissionsPartial.map((m) => m.id).sort());
    });

    test("The public baseline is unioned into a user with no grants of their own", async () => {
      // Public grants apply to everyone, so marking a mission public gives a grantless user that
      // mission and nothing else of this test's set.
      const em = globalValues.orm.em.fork();
      await grantMissionPerms(em, {
        missionId: testMissionsPartial[2].id,
        userId: publicUser.id,
        permLevel: "viewer",
      });

      const res = await supertest(app)
        .get("/api/v1/missionHomepageItems")
        .set(asUser(NO_PERMS_UUPIC));

      expect(res.statusCode).toBe(200);
      expect(ownIds(res.body)).toEqual([testMissionsPartial[2].id]);
    });

    test("The public baseline never downgrades a stronger grant", async () => {
      const res = await supertest(app)
        .get("/api/v1/missionHomepageItems")
        .set(asUser(GRANTED_UUPIC));

      // Their own mission plus the public one; the direct grant is not lost.
      expect(res.statusCode).toBe(200);
      expect(ownIds(res.body).sort()).toEqual(
        [testMissionsPartial[0].id, testMissionsPartial[2].id].sort()
      );
    });
  });
});

afterAll(async () => {
  const em = globalValues.orm.em.fork();
  for (const listing of testAutomergeDocListings) {
    await em.nativeDelete(Mission_Permission_db, { missionId: listing.missionId });
    await em.nativeDelete(Doc_Listing_db, { missionId: listing.missionId });
  }
  await em.nativeDelete(App_User_db, {
    uupic: { $in: [GRANTED_UUPIC, SUPER_UUPIC, NO_PERMS_UUPIC] },
  });

  // Closing the DB connection allows Vitest to exit successfully.
  await globalValues.orm.close();
  globalValues.orm = null;

  vi.restoreAllMocks();
});
