import { MikroORM } from "@mikro-orm/postgresql";
import config from "server/database/mikro-orm.config";
import { globalValues } from "server/express/global";
import { Doc_Listing_db, App_User_db } from "server/database/models/_allModels";
import DocListingFactory from "../../fixtures/entityFactories/DocListingFactory";
import AppUserFactory from "../../fixtures/entityFactories/AppUserFactory";
import supertest from "supertest";
import app from "server/express/restApi";
import { createMockAutomergeRepo } from "../../helpers/mockAutomergeRepo";
import { generateBlankEVA } from "store/storeUtils/eva";
import { generateBlankRex } from "store/storeUtils/rex";

let testAutomergeDocListings: Doc_Listing_db[];
let testMissionsPartial: Partial<Mission>[];
let asPlannedEva0: Eva;
let asPlannedEva1: Eva;
let rexEva0: Eva;
let rexEva1: Eva;
let testAppUser: App_User_db;
let noPermsAppUser: App_User_db;
const emssToken = process.env.EMSS_TOKEN;

// 30s timeout to guard against slow MikroORM.init under concurrent test load
beforeAll(async () => {
  // Initialize MikroORM and set it in globalValues
  globalValues.orm = await MikroORM.init(config);
  const em = globalValues.orm.em.fork();

  // Create 2 mission doc listings so we get autogenerated mission IDs that
  // line up with the mock automerge mission docs we'll register below.
  testAutomergeDocListings = await new DocListingFactory(em)
    .each((record, index) => {
      record.automergeUrl = `automerge:VitestTestMissionMaegistroV2Eva${index + 1}`;
    })
    .create(2);

  // Build EVAs: 2 as-planned (sharing refUuids with 2 rex-eva copies).
  asPlannedEva0 = generateBlankEVA({ name: "Vitest AsPlanned EVA 0" });
  asPlannedEva1 = generateBlankEVA({ name: "Vitest AsPlanned EVA 1" });
  rexEva0 = generateBlankEVA({
    name: "Vitest Rex EVA 0",
    refUuid: asPlannedEva0.refUuid,
  });
  rexEva1 = generateBlankEVA({
    name: "Vitest Rex EVA 1",
    refUuid: asPlannedEva1.refUuid,
  });

  const rexes = [
    generateBlankRex({ name: "Vitest REX-0", evaUuid: rexEva0.uuid }),
    generateBlankRex({ name: "Vitest REX-1", evaUuid: rexEva1.uuid }),
  ];

  const mission1Evas: Record<string, Eva> = {};
  for (const e of [asPlannedEva0, asPlannedEva1, rexEva0, rexEva1]) {
    mission1Evas[e.uuid] = e;
  }
  const mission1Rexes: Record<string, Rex> = {};
  for (const r of rexes) {
    mission1Rexes[r.uuid] = r;
  }

  testMissionsPartial = [
    {
      id: testAutomergeDocListings[0].missionId,
      name: "Vitest Test Mission Maegistro V2 Eva 1",
      archivedAt: null,
      evas: mission1Evas,
      rexes: mission1Rexes,
    },
    {
      id: testAutomergeDocListings[1].missionId,
      name: "Vitest Test Mission Maegistro V2 Eva 2",
      archivedAt: null,
      evas: {},
      rexes: {},
    },
  ];

  globalValues.automergeRepo = createMockAutomergeRepo(testMissionsPartial);

  // A user with view permission on mission[0] only (no perms on mission[1]).
  testAppUser = await new AppUserFactory(em).createOne({
    username: "VitestMaestroV2Eva",
    permissionList: [
      {
        missionId: testAutomergeDocListings[0].missionId,
        permissions: {
          edit: true,
          view: true,
        },
      },
    ],
  });

  // A user with no perms on any of our test missions.
  noPermsAppUser = await new AppUserFactory(em).createOne({
    username: "VitestMaestroV2EvaNoPerms",
  });
}, 30000);

describe("READABLE EVA Endpoint (Maegistro V2)", () => {
  describe("Authentication", () => {
    test("Fails without any auth", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/eva")
        .query({ missionId: testAutomergeDocListings[0].missionId });
      expect(res.statusCode).toBe(401);
      expect(res.body.status).toBe("failure");
      expect(res.body.message).toBe("Unauthorized");
    });

    test("Fails with invalid emss-token", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/eva")
        .set("emss-token", "invalid-token")
        .query({ missionId: testAutomergeDocListings[0].missionId });
      expect(res.statusCode).toBe(401);
      expect(res.body.status).toBe("failure");
      expect(res.body.message).toBe("Unauthorized");
    });

    test("Succeeds with valid emss-token", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/eva")
        .set("emss-token", emssToken)
        .query({ missionId: testAutomergeDocListings[0].missionId });
      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
    });

    test("Fails via login session when user has no perms on mission", async () => {
      // Login as the no-perms user.
      const loginRes = await supertest(app)
        .post("/api/v1/auth/login")
        .send({ username: noPermsAppUser.username, password: "superSecretPassword" });
      expect(loginRes.statusCode).toBe(200);
      const cookies = loginRes.header["set-cookie"];

      const res = await supertest(app)
        .get("/api/v1/maestro/v2/eva")
        .set("Cookie", cookies)
        .query({ missionId: testAutomergeDocListings[0].missionId });

      expect(res.statusCode).toBe(401);
      expect(res.body.status).toBe("failure");
    });

    test("Succeeds via login session when user has view perms on mission", async () => {
      // Login as the perms user.
      await supertest(app).get("/api/v1/auth/logout");
      const loginRes = await supertest(app)
        .post("/api/v1/auth/login")
        .send({ username: testAppUser.username, password: "superSecretPassword" });
      expect(loginRes.statusCode).toBe(200);
      const cookies = loginRes.header["set-cookie"];

      const res = await supertest(app)
        .get("/api/v1/maestro/v2/eva")
        .set("Cookie", cookies)
        .query({ missionId: testAutomergeDocListings[0].missionId });

      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
    });
  });

  describe("Query validation", () => {
    test("Returns 400 when missionId is missing", async () => {
      const res = await supertest(app).get("/api/v1/maestro/v2/eva").set("emss-token", emssToken);
      expect(res.statusCode).toBe(400);
      expect(res.body.status).toBe("error");
      expect(res.body.message).toContain("Invalid mission ID");
    });

    test("Returns 400 when missionId is not a number", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/eva")
        .set("emss-token", emssToken)
        .query({ missionId: "not-a-number" });
      expect(res.statusCode).toBe(400);
      expect(res.body.status).toBe("error");
      expect(res.body.message).toContain("Invalid mission ID");
    });
  });

  describe("EVA retrieval", () => {
    test("Returns all as-planned EVAs when neither refUuid nor rexUuid is given", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/eva")
        .set("emss-token", emssToken)
        .query({ missionId: testAutomergeDocListings[0].missionId });

      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      expect(res.body.message).toBe("readable evas retrieved");
      const evas: ExportEva[] = res.body.data;
      // 2 as-planned evas returned, rex-eva copies excluded.
      expect(evas).toHaveLength(2);
      const uuids = evas.map((e) => e.uuid);
      expect(uuids).toEqual(expect.arrayContaining([asPlannedEva0.uuid, asPlannedEva1.uuid]));
      expect(uuids).not.toContain(rexEva0.uuid);
      expect(uuids).not.toContain(rexEva1.uuid);
    });

    test("Returns empty array for a mission with no EVAs", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/eva")
        .set("emss-token", emssToken)
        .query({ missionId: testAutomergeDocListings[1].missionId });
      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      expect(res.body.data).toEqual([]);
    });

    test("Returns only the as-planned EVA matching refUuid", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/eva")
        .set("emss-token", emssToken)
        .query({
          missionId: testAutomergeDocListings[0].missionId,
          refUuid: asPlannedEva0.refUuid,
        });

      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      const evas: ExportEva[] = res.body.data;
      expect(evas).toHaveLength(1);
      // The as-planned copy, not the rex-eva copy.
      expect(evas[0].uuid).toBe(asPlannedEva0.uuid);
    });

    test("Returns empty array when refUuid does not match any EVA", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/eva")
        .set("emss-token", emssToken)
        .query({
          missionId: testAutomergeDocListings[0].missionId,
          refUuid: "non-existent-ref-uuid",
        });

      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      expect(res.body.data).toEqual([]);
    });

    test("Returns the rex-eva copy when rexUuid is given", async () => {
      // Find the rex uuid for rexEva0.
      const rexUuid = Object.values(testMissionsPartial[0].rexes).find(
        (r) => r.evaUuid === rexEva0.uuid
      ).uuid;
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/eva")
        .set("emss-token", emssToken)
        .query({
          missionId: testAutomergeDocListings[0].missionId,
          rexUuid,
        });

      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      const evas: ExportEva[] = res.body.data;
      expect(evas).toHaveLength(1);
      expect(evas[0].uuid).toBe(rexEva0.uuid);
    });

    test("rexUuid takes precedence over refUuid", async () => {
      const rexUuid = Object.values(testMissionsPartial[0].rexes).find(
        (r) => r.evaUuid === rexEva0.uuid
      ).uuid;
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/eva")
        .set("emss-token", emssToken)
        .query({
          missionId: testAutomergeDocListings[0].missionId,
          // A refUuid that would otherwise match asPlannedEva1
          refUuid: asPlannedEva1.refUuid,
          rexUuid,
        });

      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      const evas: ExportEva[] = res.body.data;
      expect(evas).toHaveLength(1);
      // Should return the rex-eva pointed to by rexUuid, not the as-planned eva
      // matched by refUuid.
      expect(evas[0].uuid).toBe(rexEva0.uuid);
    });

    test("Returns empty array when rexUuid does not exist", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/eva")
        .set("emss-token", emssToken)
        .query({
          missionId: testAutomergeDocListings[0].missionId,
          rexUuid: "non-existent-rex-uuid",
        });

      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      expect(res.body.data).toEqual([]);
    });

    test("Returned EVAs have ExportEva shape (_itemType, sequenceReadable, calculatedFields)", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/eva")
        .set("emss-token", emssToken)
        .query({ missionId: testAutomergeDocListings[0].missionId });
      expect(res.statusCode).toBe(200);
      const eva: ExportEva = res.body.data[0];
      expect(eva).toHaveProperty("_itemType", "EVA");
      expect(eva).toHaveProperty("sequenceReadable");
      expect(eva).toHaveProperty("sequenceRefUuids");
      expect(eva).toHaveProperty("calculatedFields");
    });
  });
});

afterAll(async () => {
  const em = globalValues.orm.em.fork();
  await em.nativeDelete(App_User_db, { username: testAppUser.username });
  await em.nativeDelete(App_User_db, { username: noPermsAppUser.username });
  for (let i = 0; i < testAutomergeDocListings.length; i++) {
    await em.nativeDelete(Doc_Listing_db, { missionId: testAutomergeDocListings[i].missionId });
  }
  await globalValues.orm.close();
  globalValues.orm = null;
  vi.restoreAllMocks();
});
