import { MikroORM } from "@mikro-orm/postgresql";
import config from "server/database/mikro-orm.config";
import { globalValues } from "server/express/global";
import { Doc_Listing_db } from "server/database/models/_allModels";
import DocListingFactory from "../../fixtures/entityFactories/DocListingFactory";
import supertest from "supertest";
import app from "server/express/restApi";
import { createMockAutomergeRepo } from "../../helpers/mockAutomergeRepo";
import { generateBlankEVA } from "store/storeUtils/eva";
import { generateBlankRex } from "store/storeUtils/rex";

let testAutomergeDocListings: Doc_Listing_db[];
let testMissionsPartial: Partial<Mission>[];
let rexEvaUuids: string[] = [];
const emssToken = process.env.EMSS_TOKEN;

beforeAll(async () => {
  // Initialize MikroORM and set it in globalValues
  globalValues.orm = await MikroORM.init(config);
  const em = globalValues.orm.em.fork();

  // 1. Create Doc_Listing_db records so we get autogenerated mission IDs that
  //    line up with the mock automerge mission docs we'll register below.
  testAutomergeDocListings = await new DocListingFactory(em)
    .each((record, index) => {
      record.automergeUrl = `automerge:VitestTestMissionV2${index + 1}`;
    })
    .create(3);

  // 2. Build EVAs and Rexes directly inside the mission docs (entity
  //    collections now live on Automerge — not in postgres).
  const evasWithRexes = [
    generateBlankEVA({ name: "Vitest EVA With Rexes 0" }),
    generateBlankEVA({ name: "Vitest EVA With Rexes 1" }),
  ];
  const evasWithoutRexes = [
    generateBlankEVA({ name: "Vitest EVA Without Rexes 0" }),
    generateBlankEVA({ name: "Vitest EVA Without Rexes 1" }),
  ];
  const evaOnV1Mission = generateBlankEVA({ name: "Vitest EVA on V1 Mission" });

  // Create rex eva versions (duplicates of as-planned evas) — only their uuid
  // matters for the rexEvaUuids filter test.
  const rexEva0 = generateBlankEVA({
    name: "Vitest Rex EVA 0",
    refUuid: evasWithRexes[0].refUuid,
  });
  const rexEva1 = generateBlankEVA({
    name: "Vitest Rex EVA 1",
    refUuid: evasWithRexes[1].refUuid,
  });
  rexEvaUuids = [rexEva0.uuid, rexEva1.uuid];

  const rexes = [
    generateBlankRex({ name: "Vitest REX-0", evaUuid: rexEva0.uuid }),
    generateBlankRex({ name: "Vitest REX-1", evaUuid: rexEva1.uuid }),
  ];

  // Mission 1: actionSystemVersion 2, has EVAs (both planned + rex copies) and rexes
  const mission1Evas: Record<string, Eva> = {};
  for (const e of [...evasWithRexes, ...evasWithoutRexes, rexEva0, rexEva1]) {
    mission1Evas[e.uuid] = e;
  }
  const mission1Rexes: Record<string, Rex> = {};
  for (const r of rexes) {
    mission1Rexes[r.uuid] = r;
  }

  // Mission 3: actionSystemVersion 1, used to be filtered out (route now does
  // not filter on actionSystemVersion, but we preserve the structure)
  const mission3Evas: Record<string, Eva> = { [evaOnV1Mission.uuid]: evaOnV1Mission };

  testMissionsPartial = [
    {
      id: testAutomergeDocListings[0].missionId,
      name: "Vitest Test Mission V2 1",
      isArchived: false,
      actionSystemVersion: 2,
      evas: mission1Evas,
      rexes: mission1Rexes,
    },
    {
      id: testAutomergeDocListings[1].missionId,
      name: "Vitest Test Mission V2 2",
      isArchived: false,
      actionSystemVersion: 2,
      evas: {},
      rexes: {},
    },
    {
      id: testAutomergeDocListings[2].missionId,
      name: "Vitest Test Mission V2 3",
      isArchived: false,
      actionSystemVersion: 1,
      evas: mission3Evas,
      rexes: {},
    },
  ];

  // Hook the mock automerge repo up so `getAutomergeMissions` reads our test
  // mission docs.
  globalValues.automergeRepo = createMockAutomergeRepo(testMissionsPartial);
});

describe("GET MISSIONS Endpoint (Maegistro V2)", () => {
  describe("Authentication", () => {
    test("Fails without emss-token", async () => {
      const res = await supertest(app).get("/api/v1/maestro/v2/getMissions");
      expect(res.statusCode).toBe(401);
      expect(res.body.status).toBe("failure");
      expect(res.body.message).toBe("Unauthorized");
    });

    test("Fails with invalid emss-token", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/getMissions")
        .set("emss-token", "invalid-token");
      expect(res.statusCode).toBe(401);
      expect(res.body.status).toBe("failure");
      expect(res.body.message).toBe("Unauthorized");
    });
  });

  describe("Missions functionality", () => {
    test("Retrieves all non-archived missions", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/getMissions")
        .set("emss-token", emssToken);
      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");

      const missions = res.body.data;
      expect(missions[testMissionsPartial[0].id]).toBeDefined();
      expect(missions[testMissionsPartial[1].id]).toBeDefined();
      expect(missions[testMissionsPartial[2].id]).toBeDefined();
    });

    test("Retrieves only as-planned EVAs (rex-eva copies are filtered out)", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/getMissions")
        .set("emss-token", emssToken);
      expect(res.statusCode).toBe(200);

      const missions: MissionsWithEvas = res.body.data;
      expect(missions[testMissionsPartial[0].id]).toBeDefined();
      // 4 as-planned evas (2 with rexes + 2 without), excluding the 2 rex-eva copies
      expect(missions[testMissionsPartial[0].id].evas).toHaveLength(4);
      // None of the returned EVAs should be one of the rex-eva copies
      expect(
        missions[testMissionsPartial[0].id].evas.some((eva) =>
          rexEvaUuids.some(
            // route exposes refUuid, but rexEvaUuids are the rex-eva's uuid;
            // a rex-eva should never appear, so a name match is good enough
            (_uuid) => eva.evaName === "Vitest Rex EVA 0" || eva.evaName === "Vitest Rex EVA 1"
          )
        )
      ).toBe(false);
    });

    test("Returns empty evas for mission with no EVAs", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/getMissions")
        .set("emss-token", emssToken);
      expect(res.statusCode).toBe(200);
      const missions: MissionsWithEvas = res.body.data;
      expect(missions[testMissionsPartial[1].id]).toBeDefined();
      expect(missions[testMissionsPartial[1].id].evas).toHaveLength(0);
    });

    test("EVAs contain refUuid + evaName", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/getMissions")
        .set("emss-token", emssToken);
      expect(res.statusCode).toBe(200);
      expect(res.body.message).toBe("Missions and their EVAs retrieved");

      const mission1Data = res.body.data[testMissionsPartial[0].id];
      const eva = mission1Data.evas[0];
      expect(eva).toHaveProperty("refUuid");
      expect(eva).toHaveProperty("evaName");
    });
  });
});

afterAll(async () => {
  const em = globalValues.orm.em.fork();
  for (let i = 0; i < testAutomergeDocListings.length; i++) {
    await em.nativeDelete(Doc_Listing_db, { missionId: testAutomergeDocListings[i].missionId });
  }
  await globalValues.orm.close();
  globalValues.orm = null;
  vi.restoreAllMocks();
});
