import { MikroORM } from "@mikro-orm/postgresql";
import config from "server/database/mikro-orm.config";
import { globalValues } from "server/express/global";
import { Doc_Listing_db, App_User_db } from "server/database/models/_allModels";
import DocListingFactory from "../../fixtures/entityFactories/DocListingFactory";
import AppUserFactory from "../../fixtures/entityFactories/AppUserFactory";
import supertest from "supertest";
import app from "server/express/restApi";
import { createMockAutomergeRepo } from "../../helpers/mockAutomergeRepo";

let testAutomergeDocListings: Doc_Listing_db[];
let testMissionsPartial: Partial<Mission>[];
let testAppUser: App_User_db;
let testSuperAdmin: App_User_db;
let noPermsAppUser: App_User_db;
const emssToken = process.env.EMSS_TOKEN;

// 30s timeout to guard against slow MikroORM.init under concurrent test load
beforeAll(async () => {
  // Initialize MikroORM and set it in globalValues
  globalValues.orm = await MikroORM.init(config);
  const em = globalValues.orm.em.fork();

  // Create 2 mission doc listings so we get autogenerated mission IDs that
  // line up with the mock automerge mission docs we'll register below.
  testAutomergeDocListings = await new DocListingFactory(em)
    .each((record, index) => {
      record.automergeUrl = `automerge:VitestTestMissionMaegistroV2Mission${index + 1}`;
    })
    .create(2);

  testMissionsPartial = [
    {
      id: testAutomergeDocListings[0].missionId,
      name: "Vitest Test Mission Maegistro V2 Mission 1",
      isArchived: false,
      // Leave grid null so route skips the getGrid/file read path.
      grid: null,
    },
    {
      id: testAutomergeDocListings[1].missionId,
      name: "Vitest Test Mission Maegistro V2 Mission 2",
      isArchived: false,
      grid: null,
    },
  ];

  globalValues.automergeRepo = createMockAutomergeRepo(testMissionsPartial);

  // A user with view perm on mission[0] only.
  testAppUser = await new AppUserFactory(em).createOne({
    username: "VitestMaestroV2Mission",
    permissionList: [
      {
        missionId: testAutomergeDocListings[0].missionId,
        permissions: {
          edit: true,
          view: true,
        },
      },
    ],
  });

  // A super admin can view all missions when no missionId given.
  testSuperAdmin = await new AppUserFactory(em).createOne({
    username: "VitestMaestroV2MissionSuperAdmin",
    isSuperAdmin: true,
  });

  // A user with no perms on any of our test missions and no global view perm.
  noPermsAppUser = await new AppUserFactory(em).createOne({
    username: "VitestMaestroV2MissionNoPerms",
  });
}, 30000);

describe("READABLE MISSION Endpoint (Maegistro V2)", () => {
  describe("Authentication with missionId", () => {
    test("Fails without any auth", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/mission")
        .query({ missionId: testAutomergeDocListings[0].missionId });
      expect(res.statusCode).toBe(401);
      expect(res.body.status).toBe("failure");
      expect(res.body.message).toBe("Unauthorized");
    });

    test("Fails with invalid emss-token", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/mission")
        .set("emss-token", "invalid-token")
        .query({ missionId: testAutomergeDocListings[0].missionId });
      expect(res.statusCode).toBe(401);
      expect(res.body.status).toBe("failure");
    });

    test("Succeeds with valid emss-token", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/mission")
        .set("emss-token", emssToken)
        .query({ missionId: testAutomergeDocListings[0].missionId });
      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
    });

    test("Fails when user has no perms on the mission", async () => {
      const loginRes = await supertest(app)
        .post("/api/v1/auth/login")
        .send({ username: noPermsAppUser.username, password: "superSecretPassword" });
      expect(loginRes.statusCode).toBe(200);
      const cookies = loginRes.header["set-cookie"];

      const res = await supertest(app)
        .get("/api/v1/maestro/v2/mission")
        .set("Cookie", cookies)
        .query({ missionId: testAutomergeDocListings[0].missionId });

      expect(res.statusCode).toBe(401);
    });

    test("Succeeds when user has view perms on the mission", async () => {
      await supertest(app).get("/api/v1/auth/logout");
      const loginRes = await supertest(app)
        .post("/api/v1/auth/login")
        .send({ username: testAppUser.username, password: "superSecretPassword" });
      expect(loginRes.statusCode).toBe(200);
      const cookies = loginRes.header["set-cookie"];

      const res = await supertest(app)
        .get("/api/v1/maestro/v2/mission")
        .set("Cookie", cookies)
        .query({ missionId: testAutomergeDocListings[0].missionId });

      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
    });
  });

  describe("Authentication without missionId", () => {
    test("Fails without any auth", async () => {
      const res = await supertest(app).get("/api/v1/maestro/v2/mission");
      expect(res.statusCode).toBe(401);
      expect(res.body.status).toBe("failure");
    });

    test("Fails via login session when user has no view perms anywhere", async () => {
      await supertest(app).get("/api/v1/auth/logout");
      const loginRes = await supertest(app)
        .post("/api/v1/auth/login")
        .send({ username: noPermsAppUser.username, password: "superSecretPassword" });
      expect(loginRes.statusCode).toBe(200);
      const cookies = loginRes.header["set-cookie"];

      const res = await supertest(app).get("/api/v1/maestro/v2/mission").set("Cookie", cookies);
      expect(res.statusCode).toBe(401);
    });

    test("Succeeds with valid emss-token", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/mission")
        .set("emss-token", emssToken);
      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
    });
  });

  describe("Mission retrieval", () => {
    test("Retrieves a specific mission when missionId is given", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/mission")
        .set("emss-token", emssToken)
        .query({ missionId: testAutomergeDocListings[0].missionId });
      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      expect(res.body.message).toBe("mission retrieved");
      const missions: ExportMission[] = res.body.data;
      expect(missions).toHaveLength(1);
      expect(missions[0].id).toBe(testAutomergeDocListings[0].missionId);
      expect(missions[0].name).toBe("Vitest Test Mission Maegistro V2 Mission 1");
    });

    test("Retrieves all missions for emss-token user when no missionId is given", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/mission")
        .set("emss-token", emssToken);
      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      const missions: ExportMission[] = res.body.data;
      const ids = missions.map((m) => m.id);
      expect(ids).toEqual(
        expect.arrayContaining([
          testAutomergeDocListings[0].missionId,
          testAutomergeDocListings[1].missionId,
        ])
      );
    });

    test("Retrieves all missions for super admin when no missionId is given", async () => {
      await supertest(app).get("/api/v1/auth/logout");
      const loginRes = await supertest(app)
        .post("/api/v1/auth/login")
        .send({ username: testSuperAdmin.username, password: "superSecretPassword" });
      expect(loginRes.statusCode).toBe(200);
      const cookies = loginRes.header["set-cookie"];

      const res = await supertest(app).get("/api/v1/maestro/v2/mission").set("Cookie", cookies);
      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      const missions: ExportMission[] = res.body.data;
      const ids = missions.map((m) => m.id);
      expect(ids).toEqual(
        expect.arrayContaining([
          testAutomergeDocListings[0].missionId,
          testAutomergeDocListings[1].missionId,
        ])
      );
    });

    test("Regular user without missionId gets only missions they have view perms on", async () => {
      await supertest(app).get("/api/v1/auth/logout");
      const loginRes = await supertest(app)
        .post("/api/v1/auth/login")
        .send({ username: testAppUser.username, password: "superSecretPassword" });
      expect(loginRes.statusCode).toBe(200);
      const cookies = loginRes.header["set-cookie"];

      const res = await supertest(app).get("/api/v1/maestro/v2/mission").set("Cookie", cookies);
      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      const missions: ExportMission[] = res.body.data;
      const ids = missions.map((m) => m.id);
      expect(ids).toContain(testAutomergeDocListings[0].missionId);
      expect(ids).not.toContain(testAutomergeDocListings[1].missionId);
    });

    test("Returned mission has ExportMission shape (gridCoordinates field)", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/mission")
        .set("emss-token", emssToken)
        .query({ missionId: testAutomergeDocListings[0].missionId });
      expect(res.statusCode).toBe(200);
      const mission: ExportMission = res.body.data[0];
      expect(mission).toHaveProperty("gridCoordinates");
      expect(mission).toHaveProperty("id");
      expect(mission).toHaveProperty("name");
    });
  });
});

afterAll(async () => {
  const em = globalValues.orm.em.fork();
  await em.nativeDelete(App_User_db, { username: testAppUser.username });
  await em.nativeDelete(App_User_db, { username: testSuperAdmin.username });
  await em.nativeDelete(App_User_db, { username: noPermsAppUser.username });
  for (let i = 0; i < testAutomergeDocListings.length; i++) {
    await em.nativeDelete(Doc_Listing_db, { missionId: testAutomergeDocListings[i].missionId });
  }
  await globalValues.orm.close();
  globalValues.orm = null;
  vi.restoreAllMocks();
});
