import { MikroORM } from "@mikro-orm/postgresql";
import config from "server/database/mikro-orm.config";
import { globalValues } from "server/express/global";
import { Doc_Listing_db, App_User_db } from "server/database/models/_allModels";
import DocListingFactory from "../../fixtures/entityFactories/DocListingFactory";
import {
  asNobody,
  asSuperUser,
  asUser,
  upsertAppUser,
  grantMissionPerms,
} from "../../fixtures/access";
import supertest from "supertest";
import app from "server/express/restApi";
import { createMockAutomergeRepo } from "../../helpers/mockAutomergeRepo";

let testAutomergeDocListings: Doc_Listing_db[];
let testMissionsPartial: Partial<Mission>[];
let testAppUser: App_User_db;
const VIEW_UUPIC = "vitest-maestro-mission-view";
const SUPER_UUPIC = "vitest-maestro-mission-super";
const NO_PERMS_UUPIC = "vitest-maestro-mission-noperms";
const emssToken = process.env.EMSS_TOKEN;

// 30s timeout to guard against slow MikroORM.init under concurrent test load
beforeAll(async () => {
  // Initialize MikroORM and set it in globalValues
  globalValues.orm = await MikroORM.init(config);
  const em = globalValues.orm.em.fork();

  // Create 2 mission doc listings so we get autogenerated mission IDs that
  // line up with the mock automerge mission docs we'll register below.
  testAutomergeDocListings = await new DocListingFactory(em)
    .each((record, index) => {
      record.automergeUrl = `automerge:VitestTestMissionMaegistroV2Mission${index + 1}`;
    })
    .create(2);

  testMissionsPartial = [
    {
      id: testAutomergeDocListings[0].missionId,
      name: "Vitest Test Mission Maegistro V2 Mission 1",
      archivedAt: null,
      // Leave serverFileGrid null so route skips the getGrid/file read path.
      serverFileGrid: null,
    },
    {
      id: testAutomergeDocListings[1].missionId,
      name: "Vitest Test Mission Maegistro V2 Mission 2",
      archivedAt: null,
      serverFileGrid: null,
    },
  ];

  globalValues.automergeRepo = createMockAutomergeRepo(testMissionsPartial);

  // A user granted mission[0] only.
  testAppUser = await upsertAppUser(em, VIEW_UUPIC);
  await grantMissionPerms(em, {
    missionId: testAutomergeDocListings[0].missionId,
    userId: testAppUser.id,
    permLevel: "edit",
  });

  // A super user reaches every mission implicitly.
  await upsertAppUser(em, SUPER_UUPIC);

  // An identity with no grants at all.
  await upsertAppUser(em, NO_PERMS_UUPIC);
}, 30000);

describe("READABLE MISSION Endpoint (Maegistro V2)", () => {
  describe("Authentication with missionId", () => {
    test("Fails for a caller holding nothing", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/mission")
        .set(asNobody())
        .query({ missionId: testAutomergeDocListings[0].missionId });
      expect(res.statusCode).toBe(401);
      expect(res.body.status).toBe("failure");
      expect(res.body.message).toBe("Unauthorized");
    });

    test("Fails with invalid emss-token", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/mission")
        .set(asNobody())
        .set("emss-token", "invalid-token")
        .query({ missionId: testAutomergeDocListings[0].missionId });
      expect(res.statusCode).toBe(401);
      expect(res.body.status).toBe("failure");
    });

    test("Succeeds with valid emss-token", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/mission")
        .set("emss-token", emssToken)
        .query({ missionId: testAutomergeDocListings[0].missionId });
      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
    });

    test("Fails when user has no grant on the mission", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/mission")
        .set(asUser(NO_PERMS_UUPIC))
        .query({ missionId: testAutomergeDocListings[0].missionId });

      expect(res.statusCode).toBe(401);
    });

    test("Succeeds when user has a grant on the mission", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/mission")
        .set(asUser(VIEW_UUPIC))
        .query({ missionId: testAutomergeDocListings[0].missionId });

      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
    });
  });

  describe("Authentication without missionId", () => {
    // There is no unauthenticated case here: with MOCK_USER the default identity always resolves,
    // and in a deployment nginx gates the route before any AEGIS code runs.

    test("A user with no grants cannot reach this test's missions", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/mission")
        .set(asUser(NO_PERMS_UUPIC));

      // They may still reach public missions, so assert on this test's set rather than the
      // status code, which depends on whether the shared database has any public grants.
      const ids: number[] = (res.body.data ?? []).map((m: ExportMission) => m.id);
      expect(ids).not.toContain(testAutomergeDocListings[0].missionId);
      expect(ids).not.toContain(testAutomergeDocListings[1].missionId);
    });

    test("Succeeds with valid emss-token", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/mission")
        .set("emss-token", emssToken);
      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
    });
  });

  describe("Mission retrieval", () => {
    test("Retrieves a specific mission when missionId is given", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/mission")
        .set("emss-token", emssToken)
        .query({ missionId: testAutomergeDocListings[0].missionId });
      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      expect(res.body.message).toBe("mission retrieved");
      const missions: ExportMission[] = res.body.data;
      expect(missions).toHaveLength(1);
      expect(missions[0].id).toBe(testAutomergeDocListings[0].missionId);
      expect(missions[0].name).toBe("Vitest Test Mission Maegistro V2 Mission 1");
    });

    test("Retrieves all missions for emss-token user when no missionId is given", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/mission")
        .set("emss-token", emssToken);
      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      const missions: ExportMission[] = res.body.data;
      const ids = missions.map((m) => m.id);
      expect(ids).toEqual(
        expect.arrayContaining([
          testAutomergeDocListings[0].missionId,
          testAutomergeDocListings[1].missionId,
        ])
      );
    });

    test("Retrieves all missions for a super user when no missionId is given", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/mission")
        .set(asSuperUser(SUPER_UUPIC));
      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      const missions: ExportMission[] = res.body.data;
      const ids = missions.map((m) => m.id);
      expect(ids).toEqual(
        expect.arrayContaining([
          testAutomergeDocListings[0].missionId,
          testAutomergeDocListings[1].missionId,
        ])
      );
    });

    test("Regular user without missionId gets only the missions they are granted", async () => {
      const res = await supertest(app).get("/api/v1/maestro/v2/mission").set(asUser(VIEW_UUPIC));
      expect(res.statusCode).toBe(200);
      expect(res.body.status).toBe("success");
      const missions: ExportMission[] = res.body.data;
      const ids = missions.map((m) => m.id);
      expect(ids).toContain(testAutomergeDocListings[0].missionId);
      expect(ids).not.toContain(testAutomergeDocListings[1].missionId);
    });

    test("Returned mission has ExportMission shape (gridCoordinates field)", async () => {
      const res = await supertest(app)
        .get("/api/v1/maestro/v2/mission")
        .set("emss-token", emssToken)
        .query({ missionId: testAutomergeDocListings[0].missionId });
      expect(res.statusCode).toBe(200);
      const mission: ExportMission = res.body.data[0];
      expect(mission).toHaveProperty("gridCoordinates");
      expect(mission).toHaveProperty("id");
      expect(mission).toHaveProperty("name");
    });
  });
});

afterAll(async () => {
  const em = globalValues.orm.em.fork();
  await em.nativeDelete(App_User_db, { uupic: { $in: [VIEW_UUPIC, SUPER_UUPIC] } });
  await em.nativeDelete(App_User_db, { uupic: NO_PERMS_UUPIC });
  for (let i = 0; i < testAutomergeDocListings.length; i++) {
    await em.nativeDelete(Doc_Listing_db, { missionId: testAutomergeDocListings[i].missionId });
  }
  await globalValues.orm.close();
  globalValues.orm = null;
  vi.restoreAllMocks();
});
