import type { EntityData } from "@mikro-orm/postgresql";
import { Factory } from "@mikro-orm/seeder";
import { Doc_Listing_db } from "server/database/models/_allModels";

// Factory for the Doc_Listing_db which holds all the doc listings
export default class DocListingFactory extends Factory<Doc_Listing_db> {
  model = Doc_Listing_db;
  definition(): EntityData<Doc_Listing_db> {
    return {
      // do not specify missionId so it can get autogenerated
      automergeUrl: "automerge:jestTestDocUrl",
    };
  }
}
