// This file is for use with the vscode plugin, Simple REST Client
// (https://marketplace.visualstudio.com/items?itemName=Tino.simple-rest-client)
// With the plugin installed, click the "Send Request" text that appears above the `POST` entry below to hit local dev and test the endpoint.

// IMPORTANT: When startStopExecution = "start", all other running REX records will be automatically stopped.
// Only one REX can be running at a time in the application.

// Below uuids are from the _TEST Mission (22) using the rex that has been created there. This means that the uuids will be the same in all envs since this is on prod.

// Full update with all parameters
POST http://localhost:4000/api/v1/emss/rexControl
# POST https://iron-emss-dev.fit.nasa.gov/api/v1/emss/rexControl
Content-Type: application/json
emss-token: {{$dotenv EMSS_TOKEN}}

{
  "rexUuid": "4d3eb10c-d526-44b1-90e7-fdbca3d67fb0",
  "maestroControlled": false,
  "startStopExecution": "start",
  "maestroExecutionHash": "test-execution-hash-12345",
  "maestroActivityProperties": {
    "egress": {
      "color": "#ff0000",
      "number": 1
    },
     "d275e068-d237-4b99-a1f5-74bf2fadb4e5": {
      "color": "#001aff",
      "number": 2
    },
    "ab8ffbe6-c59a-48ce-9f2b-64e562fd1216": {
      "color": "#ff00ff",
      "number": 3
    }
   
  }
}


###

// Only stop execution
POST http://localhost:4000/api/v1/emss/rexControl
Content-Type: application/json
emss-token: {{$dotenv EMSS_TOKEN}}

{
  "rexUuid": "4d3eb10c-d526-44b1-90e7-fdbca3d67fb0",
  "startStopExecution": "stop"
}

###

// Only set maestro control
POST http://localhost:4000/api/v1/emss/rexControl
Content-Type: application/json
emss-token: {{$dotenv EMSS_TOKEN}}

{
  "rexUuid": "4d3eb10c-d526-44b1-90e7-fdbca3d67fb0",
  "maestroControlled": false
}

###

// Only update execution hash
POST http://localhost:4000/api/v1/emss/rexControl
Content-Type: application/json
emss-token: {{$dotenv EMSS_TOKEN}}

{
  "rexUuid": "4d3eb10c-d526-44b1-90e7-fdbca3d67fb0",
  "maestroExecutionHash": "new-hash-98765"
}

###

// Combination: enable control and start execution
POST http://localhost:4000/api/v1/emss/rexControl
Content-Type: application/json
emss-token: {{$dotenv EMSS_TOKEN}}

{
  "rexUuid": "4d3eb10c-d526-44b1-90e7-fdbca3d67fb0",
  "maestroControlled": true,
  "startStopExecution": "start"
}
